- cli/CHANGELOG.md
- cli/package-lock.json
- cli/src/index.ts
> fix CLI not running on some linux distros, fixes #14

- mirrord-layer/src/lib.rs
An issue was encountered on the following system:
```
mehula@mehul-machine:~/mirrord$ uname -a
Linux mehul-machine 5.13.0-1022-azure #26~20.04.1-Ubuntu SMP Thu Apr 7 19:42:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
where `LD_PRELOAD=/home/mehula/mirrord/target/debug/libmirrord.so node sample/app.js` would fail with the following error:
```
2022-05-05T17:46:41.820500Z DEBUG mirrord: send message to client 80
2022-05-05T17:46:43.970924Z DEBUG mirrord: new connection id: 0
events.js:174
throw er; // Unhandled 'error' event
^
Error: accept EINVAL
at TCP.onconnection (net.js:1497:24)
Emitted 'error' event at:
at TCP.onconnection (net.js:1497:10)
```
The linux manpage describes the accept4 extension https://man7.org/linux/man-pages/man2/accept.2.html, which could have been the probably …
> Hook libuv uv__accept4, accept4

- .github/workflows/ci.yaml
- .vscode/launch.json
- Cargo.lock
- mirrord-layer/Cargo.toml
- mirrord-layer/src/config.rs
- mirrord-layer/src/lib.rs
- mirrord-layer/src/pod_api.rs
- mirrord-layer/src/sockets.rs
- sample/app.js
Move all socket management to separate file
> Move some functionality to separate files

- .cargo/config.toml
- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- mirrord-agent/Dockerfile
- mirrord-cli/CHANGELOG.md
- mirrord-cli/Cargo.toml
- mirrord-cli/LICENSE
- mirrord-cli/README.md
- mirrord-cli/src/main.rs
- mirrord-layer/Cargo.toml
- rust-toolchain.toml
Should merge only after https://github.com/metalbear-co/mirrord/pull/33
> Implement Mirrord CLI

- mirrord-layer/src/pod_api.rs
It looks like Job creation and pod listing happens too fast, such that the pod has not been created yet and this leads to the following panic:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', mirrord-layer/src/pod_api.rs:127:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
`let pod = pods.items.first().unwrap();`
We use the watch API and wait till the resource has been added. https://docs.rs/kube/latest/kube/struct.Api.html#method.watch
> Add watch on pod creation

- mirrord-layer/src/lib.rs
Still not the best solution, as error handling is (mostly) missing, but I believe this will be a quality of life improvement.
> Refactoring `mirrord-layer` `select!` body into functions.

- .github/workflows/release.yaml
Add a CI workflow to publish the VSCode extension for all supported platforms.
> Publish ext in ci

- .github/workflows/release.yaml
So we can test from other branches
> Add release.yaml

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- mirrord-layer/src/config.rs
- mirrord-layer/src/lib.rs
Add release YAML for releasing VS Code Extension, Docker image and binaries.
> Release yaml

- .github/workflows/release.yaml
- vscode-ext/libmirrord_layer.dylib
- vscode-ext/libmirrord_layer.so
- Path to artifacts was wrong.
- VS Code doesn't like pre release versions
> Fix release

- mirrord-layer/src/config.rs
- mirrord-layer/src/lib.rs
Fixes some issues that I missed.
> Add file ops to config. Fix close_detour taking into account the wrong flag for enabling file ops.

- CHANGELOG.md
- Cargo.lock
- mirrord-cli/Cargo.toml
- mirrord-cli/src/main.rs
This will download and use x64 binary when needed.
> Support running emulated processes on m1 using mirrord

- .github/workflows/ci.yaml
- CHANGELOG.md
- tests/app.yaml
- tests/node-e2e/app.js
- tests/python-e2e/app.py
- tests/src/sanity.rs
- tests/src/utils.rs
> E2E small improvements, removing sleeps

- CHANGELOG.md
- mirrord-cli/src/main.rs
Adding in a CLI arg for an Agent TTL
> Add CLI arg for Agent TTL

- CHANGELOG.md
- mirrord-layer/src/pod_api.rs
Re https://github.com/metalbear-co/mirrord/issues/110
I'm not sure if this is it or you had something more complex in mind...
btw - it's hard to test changes locally without some kind of a guide/documentation on how to setup a proper local testing env
> Issue110 - Adding context to error instead of unwrap

- CHANGELOG.md
- mirrord-layer/src/sockets.rs
- tests/src/sanity.rs
> Fix fcntl m1

- CHANGELOG.md
- mirrord-layer/src/lib.rs
changed from unwrap to unwrap_or_else panic
> fixed unwraps inside of mirrord agent creation

- CHANGELOG.md
- mirrord-agent/src/main.rs
- mirrord-layer/src/common.rs
- mirrord-layer/src/file.rs
- mirrord-layer/src/file/ops.rs
- mirrord-layer/src/lib.rs
- mirrord-protocol/src/codec.rs
- tests/src/sanity.rs
> Layer refactor

- tests/src/sanity.rs
We were running the test with `-d true` which is probably the reason it was not erroring out
Closes #224
> Fix dns test

- CHANGELOG.md
- Cargo.lock
- mirrord-layer/Cargo.toml
- mirrord-layer/src/error.rs
- mirrord-layer/src/socket.rs
- mirrord-layer/src/socket/ops.rs
Should fix the changes in Rust's IP format.
> Use socket2::SockAddr.

- .github/workflows/ci.yaml
- CHANGELOG.md
- mirrord-agent/src/sniffer.rs
- mirrord-agent/tests/blackbox.rs
- mirrord-layer/src/tcp.rs
- mirrord-protocol/src/tcp.rs
- tests/src/sanity.rs
Add `Subscribed` message sent from Daemon to Layer so Layer can now wait on this message in tests.
> reduce e2e flakiness

- .github/workflows/ci.yaml
- CHANGELOG.md
- mirrord-layer/src/config.rs
- mirrord-layer/src/pod_api.rs
- tests/src/sanity.rs
> e2e: increase start timeout on macOS

- CHANGELOG.md
- mirrord-layer/src/file/hooks.rs
- mirrord-layer/src/lib.rs
- mirrord-layer/src/socket/hooks.rs
- mirrord-macro/src/lib.rs
prevent calling detours from our code using DetourGuard
> prevent calling detours from our code using DetourGuard

- CHANGELOG.md
- mirrord-layer/src/file/hooks.rs
post #253 some calls do need to propagate.
> Extract reused detour logic to unguarded functions

- CHANGELOG.md
- mirrord-layer/src/pod_api.rs
References Issue #174
Remove `unwraps` by returning `Result`
> refactor: Remove unwrap and handle errors

- CHANGELOG.md
- mirrord-layer/src/common.rs
- mirrord-layer/src/error.rs
- mirrord-layer/src/file/hooks.rs
- mirrord-layer/src/file/ops.rs
- mirrord-layer/src/socket.rs
- mirrord-layer/src/socket/hooks.rs
- mirrord-layer/src/socket/ops.rs
- mirrord-layer/src/tcp.rs
> mirrord-layer: Split error LayerError Enum into two

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- mirrord-agent/Dockerfile
- mirrord-auth/Cargo.toml
- mirrord-auth/README.md
- mirrord-auth/src/lib.rs
- mirrord-cli/Cargo.toml
- mirrord-cli/src/config.rs
- mirrord-cli/src/main.rs
Add login feature to mirrord-cli
> metalbear-cloud login

- mirrord-cli/src/config.rs
- mirrord-cli/src/main.rs
> Temporary Disable Login

- CHANGELOG.md
- Cargo.lock
- mirrord-layer/Cargo.toml
- mirrord-layer/src/go_env.rs
- mirrord-layer/src/lib.rs
> go_env hook: use a different stack for the hook execution

- sample/kubernetes/app.yaml
Add a config file to the sample app to facilitate https://github.com/metalbear-co/mirrord.dev/pull/26
> Add Resources Config file for sample app.

- CHANGELOG.md
- mirrord-agent/src/dns.rs
- mirrord-agent/src/error.rs
- mirrord-agent/src/main.rs
- mirrord-agent/tests/blackbox.rs
- mirrord-layer/src/error.rs
- mirrord-layer/src/socket/hooks.rs
- mirrord-protocol/src/error.rs
- tests/src/sanity.rs
Closes https://github.com/metalbear-co/mirrord/issues/321
> remote dns doesnt work for nodejs

- CHANGELOG.md
- mirrord-cli/src/main.rs
- tests/src/sanity.rs
> Warning when using remote tcp without remote DNS 

- .github/workflows/release.yaml
- CHANGELOG.md
Adressing https://github.com/metalbear-co/mirrord/issues/337
> Include apple dylib in intelliJ-ext.

- CHANGELOG.md
- mirrord-layer/src/lib.rs
- mirrord-layer/src/pod_api.rs
> mirrord-layer: User-friendly accept_invalid_certificates Error

- .github/workflows/release.yaml
- .vscode/launch.json
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- intellij-ext/gradle.properties
- tests/go-e2e/main.go
- vscode-ext/package-lock.json
- vscode-ext/package.json
> MVP - 3.0.0 alpha release!

- .github/workflows/arch_cli_sign.json
- .github/workflows/arch_dylib_sign.json
- .github/workflows/release.yaml
- .github/workflows/universal_cli_sign.json
- .github/workflows/universal_dylib_sign.json
- CHANGELOG.md
> add codesign for Apple binaries

- mirrord-layer/src/config.rs
- mirrord-layer/src/pod_api.rs
> Default agent namespace to same as pod if not provided

- .github/workflows/ci.yaml
- CHANGELOG.md
- intellij-ext/build.gradle.kts
> IntelliJ Ext: Add Exception if shared lib is not found

- .devcontainer/Dockerfile
- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- CHANGELOG.md
- rust-toolchain.toml
> Revert "Pin nightly compiler to 2022-09-13"

- CHANGELOG.md
- mirrord-layer/src/file/hooks.rs
> Fix tracing error from write_detour on stdout/stderr

- CHANGELOG.md
- intellij-ext/build.gradle.kts
- intellij-ext/src/main/kotlin/com/metalbear/mirrord/MirrordEnabler.kt
- intellij-ext/src/main/kotlin/com/metalbear/mirrord/MirrordListener.kt
refer #317 
refer: https://stackoverflow.com/questions/54826606/intellij-plugin-access-is-allowed-from-event-dispatch-thread-only
https://intellij-support.jetbrains.com/hc/en-us/community/posts/7602780460306-Access-is-allowed-from-event-dispatch-thread-only
> Intellij Ext: Fix "access is allowed from event dispatch thread"

- .github/workflows/arch_dylib_sign.json
- .github/workflows/release.yaml
- CHANGELOG.md
> Bundle arm64 binary into the universal binary for MacOS.

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- intellij-ext/gradle.properties
- vscode-ext/package-lock.json
- vscode-ext/package.json
> 3.0.9-alpha

- CHANGELOG.md
- tests/Cargo.toml
> Fix unused manifest key

- CHANGELOG.md
- mirrord-layer/src/error.rs
> Don't report InProgress io error as error (log as info)

- CHANGELOG.md
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordExecDialog.kt
> Make Dialog list for intellij sorted + add search bar

- CHANGELOG.md
- intellij-ext/build.gradle.kts
- intellij-ext/gradle.properties
- intellij-ext/src/main/resources/META-INF/plugin.xml
> remove future limit on JetBrains

- CHANGELOG.md
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordExecDialog.kt
> jetbrains: better targets UX

- .github/workflows/ci.yaml
- CHANGELOG.md
Fixes https://github.com/metalbear-co/mirrord/issues/251
> Fix Cache doesn't work on test-agent workflow

- CHANGELOG.md
- mirrord/cli/src/main.rs
- mirrord/kube/src/api/container.rs
> Filter out agent pods from mirrord ls

- CHANGELOG.md
- mirrord/sip/src/lib.rs
#951. Thought this would help me with another PR. It did not, but at least we can close this issue.
> Don't exit on SIP-check fail, show error.

- CHANGELOG.md
- mirrord/cli/src/main.rs
- vscode-ext/src/extension.ts
Prevent the target prompt from showing twice
closes #1080
> Fix VSCode Ext Double Prompt

- Cargo.lock
- mirrord/config/Cargo.toml
- mirrord/console/Cargo.toml
- mirrord/layer/Cargo.toml
- mirrord/layer/tests/common/mod.rs
> Unused dependencies

- CHANGELOG.md
- mirrord/cli/src/config.rs
- mirrord/cli/src/execution.rs
- mirrord/cli/src/extension.rs
- mirrord/cli/src/internal_proxy.rs
- mirrord/cli/src/main.rs
> change internal proxy timeout from extension

- CHANGELOG.md
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordExecManager.kt
- intellij-ext/modules/products/idea/src/main/kotlin/com/metalbear/mirrord/products/idea/IdeaRunConfigurationExtension.kt
> fix gradle intellij plugin

- CHANGELOG.md
- mirrord/agent/src/steal/ip_tables.rs
> Meshed stealing remove accidental outgoing capture

- CHANGELOG.md
- mirrord/config/src/fs.rs
- mirrord/config/src/fs/advanced.rs
- mirrord/config/src/lib.rs
- mirrord/kube/src/api/runtime.rs
- mirrord/layer/src/file/filter.rs
- mirrord/layer/src/load.rs
- mirrord/layer/tests/apps/fileops/src/main.rs
- mirrord/layer/tests/bash.rs
- mirrord/layer/tests/fileops.rs
- mirrord/layer/tests/http_mirroring.rs
- mirrord/layer/tests/self_connect.rs
- mirrord/layer/tests/sip.rs
- mirrord/layer/tests/spawn.rs
- tests/rust-e2e-fileops/src/main.rs
- tests/src/env.rs
- tests/src/file_ops.rs
- tests/src/http.rs
- tests/src/target.rs
- tests/src/traffic.rs
- tests/src/traffic/steal.rs
> Removed test from function names

- CHANGELOG.md
- mirrord/agent/src/runtime.rs
> handle cases in agent where 2+ containerd sockets exist

- CHANGELOG.md
- mirrord/config/src/agent.rs
- Issue: #1029 
Changes `flush_connections` default value to `true`.
> Default flush_connections option to true.

- CHANGELOG.md
- Cargo.lock
- mirrord/operator/Cargo.toml
- mirrord/operator/src/client.rs
Errors from operator websocket connection would fail silently now fixed.
> mirrord-operator: fix silent fail in communication

- Cargo.lock
- changelog.d/+print-agent-error.internal.md
- changelog.d/1178.fixed.md
- mirrord/agent/src/error.rs
- mirrord/agent/src/main.rs
- mirrord/agent/src/sniffer.rs
> fix mirroring not handling big requests #1178

- Cargo.lock
- changelog.d/1180.fixed.md
- mirrord/agent/src/env.rs
- mirrord/agent/src/main.rs
- mirrord/agent/src/runtime.rs
> fix environment regression by mixing the two approaches together.

- changelog.d/1186.fixed.md
- mirrord/agent/src/error.rs
- mirrord/agent/src/runtime.rs
+ small refactor to containerd socket evaluation
Fixes #1186
> add microk8s containerd socket path

- changelog.d/+change-log-level.changed.md
- mirrord/layer/src/outgoing/tcp.rs
- mirrord/layer/src/outgoing/udp.rs
> change outgoing connection drop to be trace instead of error

- changelog.d/1218.fixed.md
- mirrord/cli/src/connection.rs
> Fallible Operator Discover

- Cargo.lock
- changelog.d/1232.fixed.md
- mirrord/cli/Cargo.toml
- mirrord/cli/src/error.rs
- mirrord/cli/src/internal_proxy.rs
> fix #1232 by using setsid in internal proxy

- changelog.d/1239.internal.md
- mirrord/layer/src/lib.rs
- mirrord/layer/src/socket.rs
- mirrord/layer/src/socket/ops.rs
> DashMap for `SOCKETS`

- changelog.d/1240.internal.md
- mirrord/layer/src/file.rs
- mirrord/layer/src/file/ops.rs
> Use DashMap for `OPEN_DIRS`

- changelog.d/1242.internal.md
- mirrord/layer/src/lib.rs
- mirrord/layer/src/socket.rs
- mirrord/layer/src/socket/ops.rs
- mirrord/layer/src/tcp.rs
> Use DashMap for `ConnectionQueue`

- changelog.d/1241.internal.md
- mirrord/layer/src/socket/hooks.rs
- mirrord/layer/src/socket/ops.rs
> Use DashMap for `MANAGED_ADDRINFO`

- changelog.d/1280.internal.md
- mirrord/agent/Dockerfile
> optimize agent dockerfile build

- changelog.d/1291.changed.md
- mirrord/config/src/config/from_env.rs
- mirrord/config/src/target.rs
> improve bad comment error

- DEBUGGING.md
- changelog.d/1278.internal.md
> IntelliJ extension debugging guide

- Cargo.lock
- changelog.d/+update-frida.internal.md
- mirrord/layer/Cargo.toml
- mirrord/layer/src/error.rs
> revert frida update

- changelog.d/1320.fixed.md
- mirrord/layer/src/detour.rs
not crashing in case it can't update the bypass
Fixes #1320
> Change detour bypass to be more robust

- changelog.d/1347.added.md
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordExecDialog.kt
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordSettingsState.kt
> Remember last selected target in IntelliJ

- changelog.d/1380.fixed.md
- mirrord/kube/src/api.rs
- mirrord/layer/src/connection.rs
- mirrord/layer/src/lib.rs
> Fix crash on unexpected LogMessage

- changelog.d/+incluster-no-dns.internal.md
- mirrord/kube/src/api/kubernetes.rs
- mirrord/kube/src/error.rs
Remove redundant dns resolution for incluster agent connection in mirrord-kube
> Agent remove incluster dns resolution

- Cargo.lock
- changelog.d/operator-session-id.internal.md
- mirrord/cli/src/operator.rs
- mirrord/operator/Cargo.toml
- mirrord/operator/src/client.rs
- mirrord/operator/src/crd.rs
- mirrord/operator/src/lib.rs
Add x-session-id to operator request
> Operator Session ID

- changelog.d/1030.added.md
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordConfigAPI.kt
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordConfigDropDown.kt
- intellij-ext/src/main/resources/META-INF/plugin.xml
closes #1411 
note: a bit unstable rn, wip
> Config dropdown for intelliJ

- changelog.d/1337.fixed.md
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordNotifier.kt
> intelliJ progress fix

- changelog.d/1420.fixed.md
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordConfigDropDown.kt
- mirrord/cli/src/main.rs
I pushed the wrong diff in the previous PR, this fixes that.
> intelliJ: updateConfigs should be unset in the task

- changelog.d/1376.added.md
- vscode-ext/src/extension.ts
https://github.com/metalbear-co/mirrord/issues/1376
Add targetless target to dialog, notify about targetless runs.
To run targetless the user can choose the targetless target (or press escape).
> Targetless on vscode

- Cargo.lock
- Cargo.toml
- changelog.d/1397#.fixed.md
- mirrord/sip/Cargo.toml
- mirrord/sip/src/lib.rs
> Added better detection for protected binaries, fixes not loading into

- changelog.d/1441.fixed.md
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordConfigAPI.kt
> Fix misalignment on IntelliJ not accepting complex path in target

- .github/workflows/ci.yaml
- changelog.d/1431.internal.md
- mirrord/layer/tests/spawn.rs
> Fix node spawn test flakiness on macOS

- changelog.d/1456.fixed.md
- intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordNotifier.kt
- intellij-ext/src/main/resources/META-INF/plugin.xml
> Change to sticky balloon on warnings in intelliJ

- changelog.d/+rust-log.changed.md
- changelog.d/1446.fixed.md
- mirrord/agent/src/env.rs
> Add RUST_LOG to hardcoded excluded env vars.

- changelog.d/+defaults-remote.changed.md
- mirrord/layer/src/file/filter.rs
Also make the macOS relevant parts compile only on macOS.
> Add `/Volumes` to default local on macOS

- changelog.d/1012.added.md
- intellij-ext/build.gradle.kts
- intellij-ext/gradle.properties
- intellij-ext/gradle/wrapper/gradle-wrapper.properties
- intellij-ext/modules/products/pycharm/build.gradle.kts
- intellij-ext/modules/products/rider/build.gradle.kts
- intellij-ext/modules/products/rider/src/main/kotlin/com/metalbear/mirrord/products/rider/RiderPatchCommandLineExtension.kt
- intellij-ext/settings.gradle.kts
- intellij-ext/src/main/resources/META-INF/mirrord-rider.xml
- intellij-ext/src/main/resources/META-INF/plugin.xml
> Rider support added

- changelog.d/1514.fixed.md
- scripts/install.sh
> Avoid unnecessary sudo - for installing mirrord in a Dockerfile

- Cargo.lock
- Cargo.toml
- changelog.d/1512.internal.md
- mirrord/agent/Cargo.toml
- mirrord/agent/src/steal/connection.rs
- mirrord/agent/src/steal/http.rs
- mirrord/agent/src/steal/http/filter.rs
- mirrord/agent/src/steal/http/hyper_handler.rs
- mirrord/agent/src/steal/http/v1.rs
- mirrord/agent/src/steal/http/v2.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/tcp.rs
- mirrord/sip/Cargo.toml
Partial work for #1512 - would love to merge it already to avoid huge PR :)
> HTTP Path Filtering partial

- changelog.d/1534.fixed.md
- mirrord/agent/src/error.rs
- mirrord/agent/src/runtime/crio.rs
> crio openshift fix

- Cargo.lock
- changelog.d/+remove-openssl-dependency.internal.md
fixes release issue introduced in #1532
> remove openssl dependency

- .vscode/launch.json
- changelog.d/+sip-patch-vscode.fixed.md
- changelog.d/+vscode-debug.internal.md
- vscode-ext/src/extension.ts
> fix vs code sip patch not working and launch json for debugging the

- Cargo.lock
- changelog.d/+remove-open-ssl-again.internal.md
- mirrord/auth/Cargo.toml
> Remove openSSL again

- Cargo.lock
- changelog.d/+cleanup-operator.internal.md
- mirrord/auth/Cargo.toml
- mirrord/auth/src/credential_store.rs
- mirrord/cli/src/config.rs
- mirrord/cli/src/operator.rs
- mirrord/operator/src/crd.rs
don't error on missing operator credentials
> Remove unused CRD for operator and remove false error

- changelog.d/1621.changed.md
- mirrord/kube/src/api/container.rs
> Changed agent job definition to include limits

- changelog.d/+operator-setup-fix.internal.md
- mirrord/cli/src/config.rs
- mirrord/cli/src/operator.rs
- mirrord/operator/src/setup.rs
remove `--offline` option from operator setup and fix a failure point.
> Operator Setup Update

- changelog.d/1634.changed.md
- mirrord/kube/src/api/container.rs
> Changed agent job definition to tolerate everything

- changelog.d/1640.fixed.md
- mirrord/agent/src/steal/ip_tables.rs
- mirrord/agent/src/steal/ip_tables/standard.rs
> Iptables PREROUTING fallback

- Cargo.lock
- Cargo.toml
- changelog.d/+mirrord-sip-dependency-fix.internal.md
> Fix compilation of apple-codesign crate that broke due to rasn-derive.

- changelog.d/1655.fixed.md
- mirrord/agent/src/steal/ip_tables/flush_connections.rs
> Fix Flush Connections

- README.md
- changelog.d/1662.added.md
- mirrord-schema.json
- mirrord/config/src/agent.rs
- mirrord/config/src/lib.rs
- mirrord/kube/src/api/container.rs
> Disable agent capabilities

- changelog.d/+proxy-api.internal.md
- mirrord/operator/src/client.rs
- mirrord/operator/src/crd.rs
Add support for operator side feature flags & new "proxy" verb api
> Operator support Proxy Api

- Cargo.lock
- Cargo.toml
- changelog.d/1460.added.md
- mirrord/console/Cargo.toml
- mirrord/kube/src/api/container.rs
- mirrord/operator/Cargo.toml
- mirrord/operator/src/client.rs
- tests/Cargo.toml
- tests/src/pause.rs
- tests/src/traffic.rs
> Update dependencies, oidc refresh enabled in kube crate

- changelog.d/1709.fixed.md
- mirrord/layer/src/lib.rs
- mirrord/layer/src/load.rs
> Better gradle support

- Cargo.lock
- changelog.d/1721.fixed.md
- mirrord/kube/Cargo.toml
- mirrord/kube/src/api/kubernetes.rs
> Resolve tilde for kubeconfig

- changelog.d/1728.fixed.md
- mirrord/agent/src/env.rs
fixes [mirrord intellij #67](https://github.com/metalbear-co/mirrord-intellij/issues/67) and closes #1728
> Exclude environment variable COMPLUS_EnableDiagnostics

- changelog.d/1428.added.md
- mirrord/operator/src/setup.rs
> Add default user ClusterRole to operator setup

- changelog.d/1745.internal.md
- mirrord/layer/src/lib.rs
Attempt on fixing #1745 (really not sure it would fix it, since it's racy)
> Attempt to fix fork issue on macOS by avoiding access to CF on fork

- changelog.d/1745.fixed.md
- mirrord/cli/src/execution.rs
> Fix fork issue on macOS

- changelog.d/+skip-vault-supporting-containers.changed.md
- mirrord/kube/src/api/container.rs
Skip Hashicorp Vault supporting containers
> Skip Hashicorp Vault supporting containers

- Cargo.lock
- changelog.d/+.internal.md
- mirrord/agent/src/main.rs
- mirrord/kube/Cargo.toml
- mirrord/kube/src/api/container.rs
- mirrord/kube/src/error.rs
Needed for
* https://github.com/metalbear-co/mirrord-vscode/issues/50
* https://github.com/metalbear-co/mirrord-intellij/issues/79
> Print agent version in the initial message

- changelog.d/1792.fixed.md
- mirrord/layer/src/common.rs
- mirrord/layer/src/lib.rs
> Fix crash on forks by leaking HOOK_SENDER

- Cargo.lock
- changelog.d/+oop-operator.added.md
- mirrord/agent/src/main.rs
- mirrord/agent/src/steal/connection.rs
- mirrord/kube/src/api/container.rs
- mirrord/kube/src/api/runtime.rs
- mirrord/layer/src/lib.rs
- mirrord/operator/src/setup.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/codec.rs
- mirrord/protocol/src/tcp.rs
Small changes relevant to operator for #1782.
> Out of pods operator fixes

- changelog.d/1818.fixed.md
- mirrord/agent/src/main.rs
- mirrord/kube/src/api/container.rs
> Fixed environment on ephemeral container

- changelog.d/1815.added.md
- mirrord/layer/src/file/hooks.rs
> hook open64

- Cargo.lock
- changelog.d/1805.added.md
- mirrord/analytics/Cargo.toml
- mirrord/analytics/src/lib.rs
- mirrord/auth/src/certificate.rs
- mirrord/auth/src/credential_store.rs
- mirrord/auth/src/error.rs
- mirrord/cli/src/internal_proxy.rs
- mirrord/operator/Cargo.toml
- mirrord/operator/src/client.rs
> Operator Analytics Collection

- changelog.d/+warning-print.changed.md
- mirrord/progress/src/lib.rs
and not only set it as the last message of progress
> Changed CLI progress to print warnings

- changelog.d/1855.added.md
- mirrord/cli/src/error.rs
- mirrord/cli/src/execution.rs
> Report back internal proxy error stream to cli

- changelog.d/1860.changed.md
- mirrord/cli/src/execution.rs
- mirrord/cli/src/extension.rs
- mirrord/cli/src/main.rs
- mirrord/cli/src/operator.rs
- mirrord/config/derive/src/config.rs
- mirrord/config/derive/src/config/field.rs
- mirrord/config/src/agent.rs
- mirrord/config/src/config.rs
- mirrord/config/src/config/deprecated.rs
- mirrord/config/src/config/from_env.rs
- mirrord/config/src/config/source.rs
- mirrord/config/src/config/unstable.rs
- mirrord/config/src/feature/env.rs
- mirrord/config/src/feature/fs.rs
- mirrord/config/src/feature/fs/advanced.rs
- mirrord/config/src/feature/fs/mode.rs
- mirrord/config/src/feature/network.rs
- mirrord/config/src/feature/network/incoming.rs
- mirrord/config/src/feature/network/incoming/http_filter.rs
- mirrord/config/src/feature/network/outgoing.rs
- mirrord/config/src/lib.rs
- mirrord/config/src/target.rs
- mirrord/config/src/util.rs
Change config unstable/deprecations warnings to use the aggregated config warnings
Closes #1860
> Change config unstable/deprecations warnings to use the aggregated config warnings

- Cargo.lock
- Cargo.toml
- changelog.d/1869.fixed.md
- mirrord/agent/src/steal/http/v1.rs
- Issue: #1869 
Update hyper and hyper-util to get [this fix](https://github.com/hyperium/hyper/issues/3289), solving our issue with large responses and "'cannot poll Select twice'".
> Update hyper with new runtime stuff.

- changelog.d/1868.fixed.md
- mirrord/operator/src/client.rs
> Fixed detecting operator not found as an error

- changelog.d/+dont-error-on-file-not-found.fixed.md
- mirrord/layer/src/error.rs
Fixed showing error on each file not found triggered by the file not found configuration
> Fixed showing error on each file not found triggered by the file not found

- changelog.d/1811.internal.md
- tests/src/traffic/steal.rs
closes https://github.com/metalbear-co/mirrord/issues/1811
> Fix complete_passthrough response flake

- Cargo.lock
- changelog.d/+label-fastapi-flaky.internal.md
- mirrord/layer/Cargo.toml
- mirrord/layer/tests/http_mirroring.rs
> Label mirroring integration tests as flaky

- STYLE.md
- changelog.d/+style-guide-options.internal.md
This suggestion was not discussed anywhere else first, this PR is meant to be the place for objections/discussion/corrections/support.
> style guide: avoid non-optional Options

- changelog.d/+agent-single-thread.fixed.md
- mirrord/agent/src/container_handle.rs
- mirrord/agent/src/main.rs
- mirrord/agent/src/runtime.rs
- mirrord/agent/src/runtime/crio.rs
- mirrord/layer/src/lib.rs
Change agent to use current thread runtime, multi thread is enabled by mistake
> Change agent to use current thread runtime

- changelog.d/1904.fixed.md
- mirrord/agent/src/steal/ip_tables/flush_connections.rs
> Fixed agent crashing on flush connections not enabled

- .github/workflows/ci.yaml
- changelog.d/+operator-tests-ephemeral.internal.md
- tests/Cargo.toml
- tests/src/env.rs
- tests/src/file_ops.rs
- tests/src/http.rs
- tests/src/lib.rs
- tests/src/pause.rs
- tests/src/targetless.rs
- tests/src/traffic.rs
- tests/src/traffic/steal.rs
- tests/src/utils.rs
new cfg attrs to configure tests based on flags
> Enable ephemeral tests on operator

- changelog.d/1892.added.md
- mirrord/agent/src/env.rs
> Add ruby env to be excluded

- .github/workflows/ci.yaml
- .github/workflows/gh-pages.yaml
- .github/workflows/release.yaml
- CHANGELOG.md
- changelog.d/1457.internal.md
- medschool/src/main.rs
- mirrord/agent/Dockerfile
- mirrord/agent/src/file.rs
- mirrord/agent/src/main.rs
- mirrord/agent/src/steal/connection.rs
- mirrord/agent/src/util.rs
- mirrord/auth/src/credentials.rs
- mirrord/cli/src/internal_proxy.rs
- mirrord/cli/src/main.rs
- mirrord/kube/src/api/container/ephemeral.rs
- mirrord/layer/macro/src/lib.rs
- mirrord/layer/src/detour.rs
- mirrord/layer/src/exec_utils.rs
- mirrord/layer/src/file/hooks.rs
- mirrord/layer/src/outgoing/tcp.rs
- mirrord/layer/src/outgoing/udp.rs
- mirrord/layer/src/socket/ops.rs
- mirrord/layer/src/tcp_mirror.rs
- mirrord/layer/tests/apps/outgoing/src/main.rs
- mirrord/layer/tests/issue1458.rs
- mirrord/layer/tests/outgoing.rs
- mirrord/layer/tests/recv_from.rs
- rust-toolchain.toml
> Refactor code to match newest Rust nightly - 2023-09-07

- changelog.d/1928.fixed.md
- mirrord/layer/src/socket/ops.rs
> Fixed connecting to unspecified ip i.e 0.0.0.0

- Cargo.lock
- changelog.d/1962.added.md
- mirrord-schema.json
- mirrord/config/src/target.rs
- mirrord/kube/src/api/kubernetes.rs
- mirrord/kube/src/api/runtime.rs
- mirrord/operator/src/crd.rs
Added the ability to specify targetless in config file, to allow non-interactive targetless in IDEs
> Added the ability to specify targetless in config file

- Cargo.lock
- changelog.d/1972.fixed.md
- mirrord/cli/src/main.rs
> Fix progress message shows wrong latest version

- changelog.d/1983.added.md
- changelog.d/1983.fixed.md
- mirrord-schema.json
- mirrord/config/src/agent.rs
- mirrord/config/src/lib.rs
- mirrord/kube/src/api/container/job.rs
> Customize resource requests for job type agents.

- changelog.d/2014.added.md
- mirrord/agent/src/runtime.rs
Add support for k0s 
Closes #2014
> #2014 Support k0s

- Cargo.lock
- Cargo.toml
- changelog.d/2037.fixed.md
- mirrord/operator/src/crd.rs
> Fix kubernetes exec info

- .github/workflows/ci.yaml
- changelog.d/2058.fixed.md
- mirrord/layer/src/socket/ops.rs
- mirrord/layer/tests/apps/issue2058/issue2058.rs
- mirrord/layer/tests/common/mod.rs
- mirrord/layer/tests/port_mapping.rs
> Fix port mapping

- Cargo.lock
- Cargo.toml
- changelog.d/2087.added.md
- tests/src/pause.rs
- tests/src/traffic.rs
> Http proxy support

- Cargo.lock
- changelog.d/+refactor-connection.internal.md
- mirrord/agent/src/main.rs
- mirrord/agent/tests/blackbox.rs
- mirrord/cli/src/error.rs
- mirrord/cli/src/internal_proxy.rs
- mirrord/intproxy/Cargo.toml
- mirrord/intproxy/src/agent_conn.rs
- mirrord/intproxy/src/lib.rs
- mirrord/kube/src/api.rs
- mirrord/layer/tests/common/mod.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/codec.rs
This might help doing stuff around the protocol more easily.
Opening this PR now keep PRs small and also to reduce the chance for merge conflicts.
> Reduce some code duplication around agent connection and protocol

- Cargo.lock
- changelog.d/2096.added.md
- mirrord-schema.json
- mirrord/cli/src/verify_config.rs
- mirrord/config/src/feature.rs
- mirrord/config/src/feature/copy_target.rs
> Extend verify config output with compatible target types

- changelog.d/+realpath-impl.fixed.md
- mirrord/layer/src/file/hooks.rs
- mirrord/layer/src/file/ops.rs
- mirrord/layer/src/lib.rs
- mirrord/layer/tests/apps/realpath/realpath.c
- mirrord/layer/tests/common/mod.rs
Added hook for realpath function, fixing issues on files not found in Java
> Add realpath hook

- changelog.d/2140.fixed.md
- mirrord/cli/src/config.rs
> Allow license key that starts with -

- changelog.d/+readd-multi-outgoing-e2e.internal.md
- tests/node-e2e/outgoing/test_outgoing_traffic_many_requests.mjs
- tests/src/traffic.rs
test was removed here: https://github.com/metalbear-co/mirrord/pull/844
> Re-add outgoing traffic with many requests tests

- .github/workflows/ci.yaml
- changelog.d/+depcrecate-go.internal.md
- mirrord/layer/tests/apps/app_go/go.mod
- mirrord/layer/tests/apps/dir_go/go.mod
- mirrord/layer/tests/apps/dir_go_bypass/go.mod
- mirrord/layer/tests/apps/fileops/go/go.mod
- mirrord/layer/tests/apps/issue834/go.mod
- mirrord/layer/tests/apps/self_open/go.mod
- mirrord/layer/tests/common/mod.rs
- mirrord/layer/tests/fileops.rs
- mirrord/layer/tests/issue834.rs
- tests/go-e2e-dir/go.mod
- tests/go-e2e-env/go.mod
- tests/go-e2e/go.mod
- tests/src/env.rs
- tests/src/file_ops.rs
- tests/src/http.rs
- tests/src/traffic.rs
- tests/src/utils.rs
> Deprecate go 18, enable go 21

- Cargo.lock
- changelog.d/+dont-create-self-signed-cert.changed.md
- mirrord/operator/Cargo.toml
- mirrord/operator/src/setup.rs
Changed setup to not create self signed, letting operator fallback to it automatically on runtime).
Don't merge/release until operator is ready too.
https://github.com/metalbear-co/operator/issues/37
> Changed setup to not create self signed

- changelog.d/+load-agent-config-from-file.internal.md
- mirrord/config/src/agent.rs
Related: https://github.com/metalbear-co/operator/issues/287
> Add function to load agentfileconfig from path

- changelog.d/+change-not-found-order-filter.changed.md
- mirrord/layer/src/file/filter.rs
Filesystem: File not found default filter happens after checking local filter
> Filesystem: File not found default filter happens after checking local filter

- changelog.d/2164.internal.md
- mirrord-schema.json
- mirrord/config/configuration.md
- mirrord/config/src/feature/copy_target.rs
> fix copy_target config docs

- changelog.d/+report-namespace-sessions.added.md
- mirrord/cli/src/operator.rs
- mirrord/operator/src/crd.rs
- https://github.com/metalbear-co/operator/issues/362
> Report namespace for operator sessions

- Cargo.lock
- changelog.d/2246.added.md
- mirrord-schema.json
- mirrord/cli/Cargo.toml
- mirrord/cli/src/error.rs
- mirrord/cli/src/internal_proxy.rs
- mirrord/cli/src/main.rs
- mirrord/config/src/internal_proxy.rs
> Add log level and log destination for int proxy

- Cargo.lock
- changelog.d/2272.added.md
- mirrord-schema.json
- mirrord/agent/Cargo.toml
- mirrord/agent/src/main.rs
- mirrord/agent/src/steal/ip_tables.rs
- mirrord/agent/src/steal/subscriptions.rs
- mirrord/config/src/agent.rs
- mirrord/config/src/lib.rs
- mirrord/kube/src/api/container/ephemeral.rs
- mirrord/kube/src/api/container/job.rs
> add support for mesh using nftables by passing flag to agent config

- changelog.d/2281.fixed.md
- mirrord/layer/src/socket/hooks.rs
- mirrord/layer/tests/issue2055.rs
> Fix gethostbyname with disabled dns

- changelog.d/2289.fixed.md
- mirrord-schema.json
- mirrord/agent/src/outgoing/udp.rs
- mirrord/config/src/feature/network.rs
- mirrord/layer/tests/outgoing.rs
> Remove resolve_dns special handling from agent.

- changelog.d/+kuma-mesh-label.fixed.md
- mirrord/kube/src/api/container/job.rs
Added sidecar exclusion for kuma mesh fixing issues running in that setup
> Added sidecar exclusion for kuma mesh

- Cargo.lock
- changelog.d/2296.fixed.md
- mirrord/agent/src/sniffer.rs
- mirrord/agent/src/steal/ip_tables/mesh.rs
- mirrord/config/src/feature/fs/advanced.rs
- mirrord/kube/src/api/container/job.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/lib.rs
> Add Kuma detection and support to mirrord-agent

- changelog.d/+dns-cache.removed.md
- mirrord/intproxy/src/proxies/simple.rs
> Remove intproxy dns cache

- changelog.d/2309.fixed.md
- mirrord/agent/src/main.rs
- mirrord/agent/src/outgoing.rs
- mirrord/agent/src/steal/connections/filtered.rs
- mirrord/agent/src/steal/connections/unfiltered.rs
- mirrord/intproxy/src/proxies/incoming/interceptor.rs
- mirrord/intproxy/src/proxies/outgoing/interceptor.rs
- mirrord/intproxy/src/proxies/outgoing/net_protocol_ext.rs
> Handle connection shutdowns

- changelog.d/2339.fixed.md
- mirrord/cli/src/connection.rs
- mirrord/progress/src/lib.rs
> Fix new IDE progress issues

- changelog.d/2319.changed.md
- mirrord/intproxy/src/proxies/incoming.rs
- mirrord/layer/src/error.rs
- mirrord/layer/src/socket/ops.rs
- tests/node-e2e/outgoing/test_outgoing_traffic_udp_client_with_connect.mjs
- tests/src/traffic.rs
> Bind to localhost only when required (incoming)

- changelog.d/+exposed-kubernetes-api-config.internal.md
- mirrord/kube/src/api/kubernetes.rs
Purpose - to reduce cloning in the operator
> Added getters to `KubernetesAPI`

- changelog.d/2389.fixed.md
- mirrord/layer/src/socket.rs
> don't re-resolve when connecting to loopback on outgoing filter

- changelog.d/2395.added.md
- mirrord-schema.json
- mirrord/config/src/feature.rs
- mirrord/config/src/lib.rs
- mirrord/layer/src/lib.rs
> added configuratino option to control [local] hostname resolving

- changelog.d/2371.changed.md
- mirrord/layer/src/socket/ops.rs
> change port mapping/stealing/filtering logic

- changelog.d/2408.fixed.md
- mirrord/intproxy/protocol/src/lib.rs
- mirrord/intproxy/src/layer_initializer.rs
- mirrord/layer/src/lib.rs
- mirrord/layer/src/load.rs
> Fix IntelliJ Rider newest version stuck on macOS

- changelog.d/2411.fixed.md
- mirrord/layer/src/socket/ops.rs
> Fixed case where resolving DNS failed when setting HTTP filter

- changelog.d/2417.changed.md
- mirrord/agent/src/env.rs
> Changed default env exclude to have BUNDLE_WITHOUT

- changelog.d/2421.added.md
- mirrord-schema.json
- mirrord/config/src/experimental.rs
- mirrord/config/src/lib.rs
- mirrord/layer/src/setup.rs
- mirrord/layer/src/socket/ops.rs
> add experimental feature to support tcp ping for hazelcast

- CONTRIBUTING.md
- changelog.d/+contributing-guide-updated.changed.md
- Add GCC to dependencies
- Add job limit fix for RAM exhaustion
- Add missing argument to mirrord-console command
> Add edits to CONTRIBUTING.md

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- changelog.d/2438.fixed.md
- mirrord/layer/src/detour.rs
- mirrord/layer/src/socket/ops.rs
- mirrord/layer/tests/apps/issue2438/Cargo.toml
- mirrord/layer/tests/apps/issue2438/src/main.rs
- mirrord/layer/tests/common/mod.rs
- mirrord/layer/tests/outgoing.rs
> Fix outgoing connect on bound sockets

- changelog.d/2444.fixed.md
- mirrord/layer/src/setup.rs
> Fix targetless check in layer

- changelog.d/+fixed-concurrent-steal-tests.internal.md
- mirrord/cli/src/connection.rs
- mirrord/cli/src/error.rs
- mirrord/operator/src/client.rs
- mirrord/operator/src/crd.rs
- tests/src/operator/concurrent_steal.rs
- tests/src/operator/policies.rs
- tests/src/operator/sanity.rs
Following https://github.com/metalbear-co/mirrord/pull/2476
> Concurrent steal tests fixed

- Cargo.lock
- changelog.d/+downgrade-dependency.fixed.md
- mirrord/auth/Cargo.toml
- mirrord/auth/src/credentials.rs
New ring/x509-certificate breaks operator backward/forward compat https://github.com/metalbear-co/operator/issues/556
> depgrade ring and x509-certificate

- changelog.d/2526.fixed.md
- mirrord/operator/src/client.rs
> Removed misleading expiration warning from the CLI

- Cargo.lock
- changelog.d/2478.added.md
- mirrord/agent/src/steal/connection.rs
- mirrord/agent/src/steal/connections/filtered.rs
- mirrord/agent/src/steal/http.rs
- mirrord/agent/src/steal/http/body_chunks.rs
- mirrord/intproxy/Cargo.toml
- mirrord/intproxy/src/proxies/incoming.rs
- mirrord/intproxy/src/proxies/incoming/interceptor.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/tcp.rs
> Add support for chunked HTTP data requests

- changelog.d/2452.fixed.md
- mirrord/agent/src/sniffer.rs
> When using linkerd mesh use `lo` interface for mirroring traffic

- .github/workflows/ci.yaml
- Cargo.lock
- changelog.d/+key-pair-compat.internal.md
- mirrord/auth/Cargo.toml
- mirrord/auth/src/certificate.rs
- mirrord/auth/src/credential_store.rs
- mirrord/auth/src/credentials.rs
- mirrord/auth/src/error.rs
- mirrord/auth/src/key_pair.rs
Related to https://github.com/metalbear-co/operator/issues/556
> Key pair compat

- changelog.d/+operator-client-ca-role.internal.md
- mirrord/operator/src/setup.rs
relevant for metalbear-co/operator#588 & metalbear-co/operator#591
> Tls client auth

- Cargo.lock
- changelog.d/2593.internal.md
- mirrord/agent/Cargo.toml
- mirrord/agent/src/steal/connection.rs
> Add test for empty body streamed request in agent

- changelog.d/+operator-port.changed.md
- mirrord/operator/src/setup.rs
Change operator port from 3000 to 443 to allow it to work without FW exceptions.
> 3000 -> 443 operator port

- Cargo.lock
- changelog.d/2624.fixed.md
- mirrord/config/src/experimental.rs
- mirrord/layer/Cargo.toml
- mirrord/layer/src/common.rs
- mirrord/layer/src/exec_hooks/hooks.rs
- mirrord/layer/src/file.rs
- mirrord/layer/src/file/open_dirs.rs
- mirrord/layer/src/file/ops.rs
- mirrord/layer/src/lib.rs
- mirrord/layer/src/socket.rs
- mirrord/layer/src/socket/hooks.rs
- mirrord/layer/src/socket/ops.rs
Tested (manually):
- VSCode e2e
- Ruby
- Node
Closes #2624
> Fix execve

- changelog.d/2632.internal.md
- mirrord/layer/tests/common/mod.rs
> Fix layer integration tests flake

- Cargo.lock
- changelog.d/2456.fixed.md
- mirrord/agent/src/cli.rs
- mirrord/agent/src/entrypoint.rs
- mirrord/agent/src/sniffer.rs
- mirrord/agent/src/sniffer/tcp_capture.rs
- mirrord/agent/src/steal/ip_tables.rs
- mirrord/agent/src/steal/ip_tables/mesh.rs
- mirrord/agent/src/steal/ip_tables/mesh/istio.rs
- mirrord/agent/src/steal/ip_tables/output.rs
- mirrord/agent/src/steal/ip_tables/standard.rs
- mirrord/kube/src/api/container.rs
- mirrord/kube/src/api/container/ephemeral.rs
- mirrord/kube/src/api/container/pod.rs
- mirrord/kube/src/api/kubernetes.rs
- mirrord/kube/src/api/runtime.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/lib.rs
closes #2456
Add support to istio with `istio.io/dataplane-mode: ambient`
*Note update does require privileged agent to work.*
```json
{
"agnet": {
"privileged": true
}
}
```
> Istio Ambient Patch

- changelog.d/2647.fixed.md
- mirrord/config/src/feature/network/incoming.rs
- mirrord/config/src/lib.rs
> Fix breakage in simple IncomingConfig

- .github/workflows/release.yaml
- changelog.d/+fix-release-ci.internal.md
> Update CI to exclude the .dockerbuild files from release

- CHANGELOG.md
- changelog.d/+add-security-md.added.md
- changelog.d/+fix-release-ci.internal.md
> Re-Release 3.113.0

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- changelog.d/+fix-amd64-cli-image.fixed.md
- mirrord/agent/Dockerfile
- mirrord/cli/Dockerfile
Fix `arm64` version of `mirrord-cli` container image
> Fix arm64 version of mirrord-cli container image

- changelog.d/2662.fixed.md
- mirrord-schema.json
- mirrord/config/src/feature/network/incoming.rs
- mirrord/config/src/util.rs
> Fix IncomingConfig regression

- changelog.d/864.fixed.md
- mirrord/layer/src/exec_hooks.rs
- mirrord/layer/src/exec_hooks/hooks.rs
- mirrord/layer/src/file/mapper.rs
- mirrord/layer/src/socket.rs
- mirrord/layer/tests/issue864.rs
> Small fix on shared sockets

- changelog.d/2641.fixed.md
- mirrord-schema.json
- mirrord/cli/src/config.rs
- mirrord/cli/src/container.rs
- mirrord/config/configuration.md
- mirrord/config/src/container.rs
- mirrord/config/src/lib.rs
> Mark mirrord container as unstable

- Cargo.lock
- changelog.d/567.added.md
- mirrord/analytics/src/lib.rs
- mirrord/cli/Cargo.toml
- mirrord/cli/src/config.rs
- mirrord/cli/src/error.rs
- mirrord/cli/src/main.rs
- mirrord/cli/src/port_forward.rs
> Add support for port forwarding

- .github/workflows/ci.yaml
- changelog.d/+use-main-ci-action.internal.md
- Issue: N/A
Internal change to use CI action from main branch [metalbear-ci](https://github.com/metalbear-co/ci)
> Use e2e-setup-action from main tag.

- Cargo.lock
- Cargo.toml
- changelog.d/2636.internal.md
> use upstream kubers

- changelog.d/2675.fixed.md
- mirrord/operator/src/client.rs
- mirrord/operator/src/crd.rs
> fix regression in regards to split queues

- changelog.d/2680.fixed.md
- mirrord/layer/src/go/linux_aarch64.rs
> Fix hooking on arm64 Go on Linux

- changelog.d/2575.changed.md
- mirrord/cli/src/connection.rs
- mirrord/cli/src/error.rs
- mirrord/cli/src/main.rs
- mirrord/cli/src/operator.rs
- mirrord/cli/src/vpn.rs
> Specialized auth cmd error

- Cargo.lock
- changelog.d/2699.added.md
- mirrord-schema.json
- mirrord/agent/src/steal/http/filter.rs
- mirrord/cli/src/error.rs
- mirrord/cli/src/execution.rs
- mirrord/config/configuration.md
- mirrord/config/src/feature/network/incoming/http_filter.rs
- mirrord/config/src/lib.rs
- mirrord/operator/src/client.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/tcp.rs
> Advanced http filters

- changelog.d/2696.added.md
- mirrord/cli/src/config.rs
- mirrord/cli/src/port_forward.rs
> Allow hostnames in port-forward args

- Cargo.lock
- changelog.d/2713.fixed.md
- mirrord/layer/Cargo.toml
- mirrord/layer/src/setup.rs
- mirrord/layer/src/socket.rs
- mirrord/layer/src/socket/apple_dnsinfo.rs
- mirrord/layer/src/socket/hooks.rs
- mirrord/layer/src/socket/ops.rs
> Change `dns_configuration_copy` to return remote value

- changelog.d/2703.internal.md
- mirrord-schema.json
- mirrord/cli/src/connection.rs
- mirrord/cli/src/error.rs
- mirrord/cli/src/teams.rs
- mirrord/config/configuration.md
- mirrord/config/src/feature.rs
- mirrord/progress/src/messages.rs
> Add attribution to mfT docs links

- changelog.d/2738.added.md
- mirrord/kube/src/api/container.rs
> Detect Telepresence's traffic-agent and warn user about incompatibility

- Cargo.lock
- Cargo.toml
- changelog.d/2701.internal.md
- mirrord/cli/Cargo.toml
- mirrord/cli/src/connection.rs
- mirrord/progress/src/messages.rs
> Suggest mfT when user uses HTTP filter

- changelog.d/+280-mirrord-intellij-copy-target-share.internal.md
- mirrord/operator/src/client.rs
- mirrord/operator/src/crd.rs
closes metalbear-co/mirrord-intellij#280
> Simple copy-target Reuse

- Cargo.lock
- changelog.d/2759.fixed.md
- mirrord/cli/src/main.rs
- mirrord/kube/Cargo.toml
- mirrord/kube/src/api/kubernetes.rs
- mirrord/kube/src/api/kubernetes/portforwarder.rs
> Improve retry for port-forward variant of mirrord agent connection

- changelog.d/2794.fixed.md
- mirrord/agent/src/entrypoint.rs
- mirrord/agent/src/error.rs
- mirrord/agent/src/vpn.rs
Fixes #2794
Perhaps this fixes https://github.com/metalbear-co/operator/issues/649#issuecomment-2380218183
> remove vpn api use from agent for time being

- Cargo.lock
- Cargo.toml
- changelog.d/2803.fixed.md
- mirrord-schema.json
- mirrord/agent/Cargo.toml
- mirrord/kube/src/api/container/pod.rs
- mirrord/kube/src/api/runtime.rs
> Use new kube rs to support empty user

- changelog.d/2807.fixed.md
- mirrord/layer/src/error.rs
- mirrord/layer/src/socket/ops.rs
> Allow using IPv6 sockets with mirrord

- Cargo.lock
- changelog.d/2827.fixed.md
- mirrord/layer/src/debugger_ports.rs
- mirrord/layer/src/socket.rs
- mirrord/layer/src/socket/dns_selector.rs
- mirrord/layer/src/socket/ops.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/outgoing.rs
Should fix any regression caused by https://github.com/metalbear-co/mirrord/pull/2808
> Handle IPv4 in IPv6, fix regressions

- Cargo.lock
- changelog.d/2836.fixed.md
- mirrord/layer/src/debugger_ports.rs
- mirrord/layer/src/error.rs
- mirrord/layer/src/socket.rs
- mirrord/layer/src/socket/dns_selector.rs
- mirrord/layer/src/socket/ops.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/outgoing.rs
> Disallow using IPv6 sockets with mirrord

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- changelog.d/2812.fixed.md
- changelog.d/2812.internal.md
- mirrord/layer/src/socket/ops.rs
- mirrord/layer/tests/apps/rebind0/Cargo.toml
- mirrord/layer/tests/apps/rebind0/src/main.rs
- mirrord/layer/tests/common/mod.rs
- mirrord/layer/tests/configs/http_filter_for_rebind0.json
- mirrord/layer/tests/configs/http_filter_port_3000.json
- mirrord/layer/tests/rebind0.rs
- mirrord/layer/tests/warn_ignored_unfiltered_port.rs
- tests/src/utils.rs
> Add integration test, fix wrong warning

- Cargo.lock
- changelog.d/2851.added.md
- mirrord/agent/src/steal/ip_tables/mesh.rs
- mirrord/kube/src/api/container.rs
- mirrord/kube/src/api/container/ephemeral.rs
- mirrord/kube/src/api/container/pod.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/lib.rs
Closes #2851
Scenarios tested:
1. exec into pod and curl localhost -> stolen
2. via istiogateway -> stolen
3. port forward to pod -> stolen
> Added support for Istio CNI

- changelog.d/+skip-bazel.changed.md
- mirrord/layer/src/load.rs
For https://github.com/metalbear-co/mirrord-intellij/pull/292
> Skipping bazel-real as a build tool

- .github/ISSUE_TEMPLATE/bug_report.yml
- changelog.d/2664.internal.md
> Bug report template updated

- changelog.d/2862.changed.md
- mirrord-schema.json
- mirrord/config/configuration.md
- mirrord/config/src/feature/network/outgoing.rs
> Change outgoing filter from unstable to stable

- changelog.d/2368.changed.md
- mirrord/layer/src/lib.rs
> Prevent fs-mode local being overridden to localwithoverrides in targetless mode

- changelog.d/2889.changed.md
- mirrord-schema.json
- mirrord/config/src/experimental.rs
- mirrord/layer/src/error.rs
- mirrord/layer/src/file/ops.rs
> log better errors of local file creation and add option to use alterantive way

- changelog.d/2849.changed.md
- mirrord-schema.json
- mirrord/config/src/experimental.rs
- mirrord/layer/tests/issue2807.rs
> hide ipv6 interfaces by default

- changelog.d/2909.fixed.md
- mirrord/agent/src/entrypoint.rs
> Fix agent crash on sniffer failure

- changelog.d/2935.fixed.md
- mirrord/layer/tests/issue2283.rs
> Fix failing nodejs integration test on macos

- changelog.d/+retry-on-http-incomplete-message.fixed.md
- mirrord/intproxy/src/proxies/incoming.rs
- mirrord/intproxy/src/proxies/incoming/interceptor.rs
- Issue: na
- Related: https://github.com/hyperium/hyper/issues/2136
> Retry http request (intproxy) on hyper IncompleteMessage error.

- changelog.d/2944.fixed.md
- mirrord/cli/src/container.rs
> Fix race condition with container run caused by regression

- CONTRIBUTING.md
- Cargo.lock
- Cargo.toml
- changelog.d/+update-deps.internal.md
- mirrord/agent/src/dns.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/dns.rs
- mirrord/protocol/src/error.rs
Closes #2970 
Had to adapt some code even though it's just a minor version, because hickory uses [ZeroVer](https://0ver.org/).
> Update hickory, adapt code

- changelog.d/2986.changed.md
- mirrord/layer/src/debugger_ports.rs
> Changed log level for messages in debugger ports detection + style improvements

- changelog.d/+fs-policy-test.internal.md
- mirrord/operator/src/crd/policy.rs
- tests/node-e2e/fspolicy/test_operator_fs_policy.mjs
- tests/src/operator/policies.rs
- tests/src/operator/policies/fs.rs
- tests/src/utils.rs
1. The test was using a bad target path
2. Added some messages to assertions and extra debug prints in test utils
3. Changed case of `FsPolicy` fields to camelCase, because everything in our crds is camelCase
4. Changed `FsPolicy` docs a bit
> Fixed fs policy E2E test

- changelog.d/3030.fixed.md
- mirrord/cli/src/error.rs
- mirrord/cli/src/external_proxy.rs
Add ping timer to extproxy so at least one connection is kept up while it is running
> Add ping pong subtask to extproxy

- changelog.d/+fix-ipv6-link.fixed.md
- mirrord-schema.json
- mirrord/config/configuration.md
- mirrord/config/src/feature/network.rs
Closes https://github.com/metalbear-co/mirrord.dev/issues/403
> Fix ipv6 config doc

- changelog.d/3082.fixed.md
- mirrord/layer/src/file/ops.rs
- mirrord/layer/tests/apps/fileops/go/main.go
- tests/go-e2e-statfs/main.go
closes #3082
I recommend reviewing commit-by-commit and reading the commit messages.
> Respect ignored/relative/mapped paths in statfs hook

- Cargo.lock
- Cargo.toml
- changelog.d/+updated-dependencies.internal.md
- mirrord/console/src/main.rs
- mirrord/intproxy/protocol/src/codec.rs
- mirrord/intproxy/protocol/src/codec/codec_async.rs
- mirrord/protocol/Cargo.toml
- mirrord/protocol/src/codec.rs
https://rustsec.org/advisories/RUSTSEC-2025-0009
> Updated ring dependency

- README.md
> docs: added a link to the license

- README.md
> docs: added a link to the badge releases

- README.md
> docs: added badge and link to СI workflow

- changelog.d/3212.fixed.md
- mirrord/layer/src/socket/ops.rs
- mirrord/layer/tests/apps/make_connections.mjs
- mirrord/layer/tests/common/mod.rs
- mirrord/layer/tests/outgoing.rs
> Fixed: cannot connect to dapr sidecar on high port

- LICENSE
> docs(readme): updated the license data

- changelog.d/3119.changed.md
- mirrord/agent/src/steal/connections/filtered.rs
Warn clients that are below minimum protocol version required.
> fix: warn clients below required version

- changelog.d/+agent-concurrency.changed.md
- mirrord/agent/src/entrypoint.rs
- mirrord/agent/src/main.rs
- mirrord/agent/src/util/remote_runtime.rs
> Increased number of OS threads used by the agent

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- changelog.d/3250.added.md
- deny.toml
- mirrord/agent/Cargo.toml
- mirrord/layer/tests/apps/dns_resolve/Cargo.toml
- mirrord/layer/tests/apps/issue2438/Cargo.toml
- mirrord/layer/tests/apps/rebind0/Cargo.toml
- mirrord/layer/tests/apps/recv_from/Cargo.toml
- sample/rust/Cargo.toml
- tests/Cargo.toml
- tests/rust-sqs-printer/Cargo.toml
- tests/rust-websockets/Cargo.toml
Also includes a couple updates to dependencies to comply with initial deny config
> Cargo deny

- changelog.d/3220.changed.md
- mirrord/agent/env/src/mesh.rs
- mirrord/agent/iptables/src/lib.rs
- mirrord/agent/src/entrypoint.rs
> Skip iptables cleanup if done already

- changelog.d/+shared-client-version.internal.md
- mirrord/agent/src/entrypoint.rs
- mirrord/agent/src/steal.rs
- mirrord/agent/src/steal/api.rs
- mirrord/agent/src/steal/connection.rs
- mirrord/agent/src/steal/connections/filtered.rs
- mirrord/agent/src/steal/subscriptions.rs
- mirrord/agent/src/util.rs
- mirrord/agent/src/util/protocol_version.rs
Extracted from #3279 (it actually saves lines of code there)
> Introduced a shared wrapper for client's protocol version

- changelog.d/+agent-mesh-exclusion.added.md
- mirrord-schema.json
- mirrord/agent/env/src/envs.rs
- mirrord/agent/iptables/src/chain.rs
- mirrord/agent/iptables/src/lib.rs
- mirrord/agent/iptables/src/mesh.rs
- mirrord/agent/iptables/src/mesh/exclusion.rs
- mirrord/agent/iptables/src/output.rs
- mirrord/agent/src/entrypoint.rs
- mirrord/agent/src/entrypoint/setup.rs
- mirrord/agent/src/incoming.rs
- mirrord/agent/src/incoming/composed.rs
- mirrord/agent/src/incoming/iptables.rs
- mirrord/agent/src/incoming/task.rs
- mirrord/config/src/agent.rs
- mirrord/kube/src/api/container/ephemeral.rs
- tests/src/traffic.rs
> Exclude agent from mesh

- changelog.d/+asterisk-test.internal.md
- tests/src/operator/queue_splitting.rs
> E2E test for asterisk in client config together with SQS json in fallback field

- changelog.d/+add-mirrord-dump.added.md
- mirrord/analytics/src/lib.rs
- mirrord/cli/src/config.rs
- mirrord/cli/src/dump.rs
- mirrord/cli/src/error.rs
- mirrord/cli/src/main.rs
Add new command - mirrord dump -p PORT -t TARGET to get incoming traffic dump of target
> add mirrord dump command

- changelog.d/+lingering-agent.fixed.md
- mirrord/agent/src/entrypoint.rs
- mirrord/agent/src/entrypoint/setup.rs
- mirrord/agent/src/steal/task.rs
- mirrord/agent/src/steal/test.rs
- tests/src/cleanup.rs
- tests/src/lib.rs
- tests/src/misc.rs
`TcpStealerTask` was lingering forever
> Fix lingering agent

- changelog.d/3247.internal.md
- mirrord/intproxy/src/proxies/incoming/http_gateway.rs
- mirrord/layer/tests/apps/gethostbyname/gethostbyname.c
Issue: https://linear.app/metalbear/issue/MBE-849/update-mirrorddev-links
> Update links from mirrord.dev to metalbear.co/mirrord

- changelog.d/+config-agent-dns.internal.md
- mirrord-schema.json
- mirrord/config/configuration.md
- mirrord/config/src/agent.rs
Add another docstring to `AgentDnsConfig` so it will apear in docs correctly.
> AgentDnsConfig add struct doc

- changelog.d/+improve-dirty-iptables-error.internal.md
- mirrord/agent/src/entrypoint.rs
Issue: https://linear.app/metalbear/issue/MBE-1427/add-mirrord-for-teams-cta-on-dirty-iptables-error
> Improve dirty iptables error

- changelog.d/+hide-op-setup-cmd.internal.md
- mirrord/cli/src/config.rs
- mirrord/cli/src/operator.rs
- test.json
Issue: https://linear.app/metalbear/issue/MBE-1321/license-server-docs-user-facing
> Hide operator setup command
