Cargo.lock, mirrord-layer/Cargo.toml
@meowjesty found out that on Linux, with certain applications (as node) there's an OpenSSL versions conflict when linking dynamically. We avoid that by using rustls instead of openssl.
=> OpenSSL + Node issue

mirrord-cli/src/main.rs, mirrord-layer/src/config.rs, mirrord-layer/src/lib.rs, mirrord-layer/src/pod_api.rs
This is to enable better CI with non-released versions.
=> add cli arg to support setting of agent image

Cargo.lock, Cargo.toml, mirrord-cli/src/main.rs, mirrord-layer/src/config.rs, mirrord-layer/src/pod_api.rs
Following changes have been made:
- Currently certificates can't be verified in the current version of rustls for IP addresses and this results in an `invalid dnsname` error. The latest commits on rustls suppress certificate verification https://github.com/rustls/rustls/pull/1032 and we use this by patching the dependencies. 
- Added a new CLI argument which accepts boolean value to accept/reject invalid certificates. This argument is directly related to the new `MIRRORD_ACCEPT_INVALID_CERTIFICATES` environment variable (default false)
=> Accept invalid certificates optionally

.dockerignore, Cargo.lock, mirrord-agent/.dockerignore, mirrord-agent/CHANGELOG.md, mirrord-agent/Cargo.toml, mirrord-agent/Dockerfile, mirrord-agent/src/main.rs, mirrord-agent/src/sniffer.rs, mirrord-agent/tests/blackbox.rs, mirrord-layer/Cargo.toml, mirrord-layer/src/common.rs, mirrord-layer/src/config.rs, mirrord-layer/src/lib.rs, mirrord-layer/src/macros.rs, mirrord-layer/src/sockets.rs, mirrord-protocol/src/codec.rs
Refactor sockets - beforehand we created socketpair on each socket creation, now we only do it when necessary using delayed execution of bind,listen.
closes #41 closes #42
=> Refactor sockets

mirrord-layer/src/config.rs, mirrord-layer/src/pod_api.rs
Create the mirrord agent as a Kubernetes Job instead of Pod, so that it can self-terminate after completion.
=> Create mirrord agent as job instead of pod

mirrord-cli/src/main.rs
Interface to use `accept_invalid_certificates` was to supply `true`/`false` value, while it makes more sense to have it as a flag.
=> make accept_invalid_certificates a flag instead of an argument

mirrord-layer/src/sockets.rs
Make getpeername and getsockname optional as frida sometimes doesn't recognize them - possibly due to this issue: https://github.com/frida/frida-gum/issues/273
=> Make getpeername and getsockame optional

mirrord-protocol/src/codec.rs
Clippy was updated and now alerts on structs that can implement Eq but don't. Add Eq to those classes.
=> Fix clippy errors

mirrord-layer/src/sockets.rs
We had fd leak because we didn't hook close, meaning that if a socket got closed we'd still hold it in our `SOCKETS` struct.
This adds a hook for close to add removal of a fd from our data.
=> Fix fd leak

mirrord-layer/src/pod_api.rs
Just a small change `"imagePullPolicy": "IfNotPresent"` as we should be able to use local images for mirrord-agent.
https://kubernetes.io/docs/concepts/containers/images/
=> Use local agent images

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, mirrord-agent/Dockerfile, tests/Cargo.toml, tests/README.md, tests/app.yaml, tests/node-e2e/app.js, tests/node-e2e/package-lock.json, tests/src/sanity.rs, tests/src/utils.rs
This PR adds the following E2E tests:
- built with the latest agent image 
`docker build -t test . --file mirrord-agent/Dockerfile`
`minikube load image test:latest`
- **test_complete_node_api**: sends four different requests to the node server present in node-e2e
`GET, POST, PUT, DELETE`. The node process writes to it's stdout which is then checked and verified by the test. Everything runs in the default namespace. The test also verifies the agent job and pod are cleaned up.
- **test_different_pod_in_cluster**: A `PUT` request is sent to a different pod in the cluster and asserted that no action corresponding to the request takes place.
- **test_good_agent_namespace**: A new namespace is created and it is specified as the agent's namespace and four different requests are sent to verify …
=> Add E2E tests

CHANGELOG.md, tests/src/utils.rs
If `MIRRORD_CHECK_VERSION` is not set to false then a version update message is printed and we can't `read_line` and check if the server is listening or not.
=> Disable version check to false for e2e tests

.github/workflows/ci.yaml, CHANGELOG.md
This PR, splits the building of agent in a separate job which is further needed by the E2E tests.
Docker image required by the E2E tests is now cached through the build-push action.
=> Refactor CI

scripts/install.sh
Fixes non-grammatical message in the installation script
=> scripts/install.sh: improve message for non-writable install target

CHANGELOG.md, Cargo.toml
This reduces binary size and potentially can improve performance.
=> Changed release profile to strip debuginfo and enable LTO.

.github/workflows/release.yaml
Reference: https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary
=> Create macOS universal2 binaries

.github/workflows/ci.yaml, CHANGELOG.md, mirrord-layer/src/pod_api.rs, tests/src/sanity.rs
- CI: Collect mirrord-agent logs in case of failure in e2e.
- Add "app" = "mirrord" label to the agent pod for log collection at ease.
- CI: Add sleep after local app finishes loading for agent to load filter make tests less flaky.
=> CI Improvements

CHANGELOG.md, mirrord-cli/Cargo.toml
Enabling the blocking feature of the reqwest library for now, so that mirrord compiles for everyone. But it's weird that mirrord compiles on some setups on which this feature is not enabled. 
Relevant issue on Cargo: https://github.com/rust-lang/cargo/issues/10775
Relevant issue on mirrord: #152
=> Enable "blocking" feature for reqwest

CHANGELOG.md, mirrord-layer/src/pod_api.rs
Marked as draft since this is changing same file as `#168` and wanted to check for feedback on this, if more changes were intended.
1. added context to kube errors during agent  creation in mirrord-layer
2. updated CHANGELOG.md
---
Finally submitting changes to handle errors for #112. Please let me know if more was intended when handling the possible `kube::Error` cases.
I considered creating a separate error enum for these cases in `mirrord-layer/src/error.rs`. Would this be more useful/idiomatic? I think this was already discussed and in `#144`, or might be overkill for these create agent errors.
Thanks!
=> Add context to job/agent creation errors

CHANGELOG.md, mirrord-cli/src/config.rs, mirrord-cli/src/main.rs, mirrord-layer/src/config.rs, mirrord-layer/src/pod_api.rs, tests/src/sanity.rs
This CR adds an optional `MIRRORD_IMPERSONATED_CONTAINER_NAME` to specify container name within pod for #100.
This doesn't implement ignoring linkerd/envoy pods yet. Can iterate on this draft based on feedback. I suppose the best way to ignore containers like this is to filter out common container names for linkerd/envoy within a pod?
A couple things that are missing, I'll convert to draft if these are blockers.
1. add ability to set this variable in VSCode extension
2. Ignore linkerd/envoy container names
These are low effort tests and not really best practice since they won't be in CI. I can try this weekend adding a mock failure run to [sanity.rs](https://github.com/metalbear-co/mirrord/blob/main/tests/src/sanity.rs#L203-L209).
1. local GH action run manually setting …
=> Add MIRRORD_IMPERSONATED_CONTAINER_NAME var

CHANGELOG.md, mirrord-cli/src/config.rs, mirrord-cli/src/main.rs, vscode-ext/README.md, vscode-ext/package-lock.json, vscode-ext/package.json, vscode-ext/src/extension.ts, vscode-ext/tsconfig.json, vscode-ext/vscode-ext
Working on remaining action items for #100: updating CLI and VSCode Extension. 
This is kind of a large, messy PR combining both the Rust CLI + Typescript changes. I'm happy to break this apart more.
1. `cd vscode-ext && vsce package`
2. Command Palette > Install extension from `.vsxi`
3. Select `mirrord-2.3.1.vsix`
~~**WIP:** There's a bug in the quickselect handling after selecting the pod name. I'm not quite sure what I'm doing wrong but think it has something to do with not bad multi-select handling. Will study [this sample](https://github.com/microsoft/vscode-extension-samples/blob/main/quickinput-sample/src/multiStepInput.ts) a bit more.~~
**EDIT**: I think I found the bug, I needed to return the `vscode.DebugConfiguration` in all branches.
[Unlisted YT Screen Recording …
=> Add quickselect for impersonated container name, fix CLI env var name

vscode-ext/package-lock.json, vscode-ext/package.json
es5-ext 10.54+ is contains [protestware](https://medium.com/checkmarx-security/new-protestware-found-lurking-in-highly-popular-npm-package-d46f8ba67e36) which is flagged as malicious by the VSCode marketplace. Downgrade the dependency so we don't get flagged.
=> Downgrade es5-ext so we don't get flagged as malicious

CHANGELOG.md, mirrord-layer/src/lib.rs, mirrord-layer/src/socket/hooks.rs
- Refactored `mirrord-layer/lib.rs` - no more passsing many arguments
- Changed `addrinfo` to `VecDeque` - fixes a potential bug (loss of order)
=> Last layer refactor I promise

.github/workflows/ci.yaml
https://github.blog/changelog/2022-0)7-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/
=> remove macOS 10.15, deprecate

CHANGELOG.md, mirrord-cli/src/config.rs, mirrord-cli/src/main.rs, mirrord-layer/src/config.rs, mirrord-layer/src/pod_api.rs, tests/src/sanity.rs
Few reasons we decided to remove for now:
1. spec cluttering
2. can't support all features (filesystem, traffic stealing) using current feature
=> remove ephemeral containers feature

CHANGELOG.md, mirrord-agent/src/cli.rs, mirrord-agent/src/file.rs, mirrord-agent/src/main.rs, mirrord-cli/src/config.rs, mirrord-cli/src/main.rs, mirrord-layer/src/config.rs, mirrord-layer/src/lib.rs, mirrord-layer/src/pod_api.rs, tests/python-e2e/ops.py, tests/src/sanity.rs
- revert the previous commit that removed the feature 
- change path to `proc/pic/root` for fs access when pid is None
- allow fs tests to run if the default path exists
=> Restore ephemeral containers feature

.gitignore, CHANGELOG.md, Cargo.lock, rustfmt.toml, tests/Cargo.toml, tests/src/sanity.rs
With the use of wsl detection remove the requirement to use minikube if there is another Kubernetes api provided (Support Docker for Windows just like Docker for Mac)
for better windows support:
- add matching to cargo version "edition" field to rustfmt.toml 
- remove ./ from ./tests/go-e2e/go-e2e for better windows git support
=> E2E - Unify node host resolution with WSL support (for better windows development experience)

CHANGELOG.md, Cargo.lock, mirrord-agent/Cargo.toml, mirrord-agent/src/file.rs, mirrord-layer/src/file.rs, mirrord-layer/src/file/hooks.rs, mirrord-layer/src/file/ops.rs, mirrord-protocol/src/codec.rs
Support hooks for `access` & `faccessat` only for absolute paths
Relevant for #200 and #137
=> Expand fs support with access & faccessat hooks for absolute paths

.github/workflows/ci.yaml, CHANGELOG.md, tests/src/sanity.rs
#248 fighting this with my life - I think the e2e for macOS is a real overkill and we just need sanity for now.
We should add tests for `layer` and `cli` specifically to cover better though.
=> e2e macOS - reduce to one test only

.github/workflows/ci.yaml, .gitignore, .vscode/launch.json, CHANGELOG.md, mirrord-layer/src/file/hooks.rs, mirrord-layer/src/go_hooks.rs, mirrord-layer/src/lib.rs, tests/go-e2e-fileops/go.mod, tests/go-e2e-fileops/main.go, tests/python-e2e/ops.py, tests/src/sanity.rs
This PR adds support for golang fileops, closes #230 
- SYS_openat
- SYS_read
- SYS_write
- SYS_lseek
- SYS_faccessat
=> Add  support for golang fileops

.devcontainer/devcontainer.json
`rust-analyzer` extension is failing to install when initializing development container. 
Extension is referencing user/org matklad. No such extension is currently available from this profile. 
Updated reference to [rust-lang official analyzer](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer).
---
I also checked the JetBrains extensions marketplace for this users hosting of the analyzer with no luck.
If this is a private hosting of the analyzer I believe it is still valuable for community contributors to have the publicly available extension applied by default.
> feedback welcome!
=> Dev Container Update

CHANGELOG.md, intellij-ext/src/main/kotlin/com/metalbear/mirrord/MirrordListener.kt
Currently the IntelliJ Plugin does not supply the selected namespace to the layer, but just uses it to fetch pods.
This means that if the user selected a non-default namespace, the mirrord layer will not find the given pod in the default namespace and will panic.
=> Use selected namespace in IntelliJ.

mirrord-layer/src/file.rs
Exclude fs calls to venv config files
=> mirrord-layer add venv.cfg exclusion

CHANGELOG.md, tests/go-e2e/main.go
No CHANGELOG entry, since this is a minor and internal change to the tests, right?
=> In go-e2e, exit instead of sending SIGINT.

CHANGELOG.md, mirrord-agent/src/main.rs, tests/bash-e2e/env.sh, tests/go-e2e-env/main.go, tests/node-e2e/remote_env/test_remote_env_vars_does_nothing_when_not_specified.mjs, tests/node-e2e/remote_env/test_remote_env_vars_exclude_works.mjs, tests/node-e2e/remote_env/test_remote_env_vars_include_works.mjs, tests/node-e2e/remote_env/test_remote_env_vars_panics_when_both_filters_are_specified.mjs, tests/src/sanity.rs
If env variable contains '=' in it's value then the GetEnvVarsResponse is completely messed up with the key being the last env variable
Example:
```
PG_CONNECTION=postgres://localhost/?ssl_mode=disable
```
generates response 
```
DaemonMessage::GetEnvVarsResponse {
...
"postgres://localhost/?ssl_mode": "disable",
...
}!
```
=> Fix Environment parsing when value contained '='

CHANGELOG.md, mirrord-layer/src/outgoing/tcp.rs, tests/node-e2e/outgoing/test_outgoing_traffic_many_requests.mjs, tests/src/sanity.rs
- Keep reading open streams until BOTH are done.
- Add meowjesty's many-requests test.
- Fix single-request, outgoing-disabled node test.
https://github.com/metalbear-co/mirrord/issues/331
https://github.com/metalbear-co/mirrord/pull/394 solves this bug by sleeping, as implemented in tcp_mirror.rs already. This PR suggests a different approach with less uncertainty.
=> Bugfix: outgoing traffic with many requests.

CHANGELOG.md, Cargo.lock, Cargo.toml
Workaround patch for supporting Kubernetes cluster that has IP as CNAME in it's certificate due to rustls/rustls#184
workaround for #388 and #39
=> Support accessing Kubernetes cluster with IP as CNAME

tests/go-e2e-dns/go.mod
Missed the name for this go module, fixing.
=> Fix go-e2e-dns module.

.github/workflows/release.yaml, CHANGELOG.md, Cargo.lock, Cargo.toml, intellij-ext/gradle.properties, vscode-ext/package-lock.json, vscode-ext/package.json
=> 3.0.10-alpha - macOS binaries should be okay now.

CHANGELOG.md, mirrord-layer/src/socket/ops.rs
When handling an outgoing connection to localhost, check first if it's a socket we intercept/mirror, then just let it connect normally.
=> Don't proxy connections that will just connect to our process anyway

.github/workflows/ci.yaml, mirrord-layer/tests/http_mirroring.rs
The test is unstable e.g. https://github.com/metalbear-co/mirrord/actions/runs/3220168873/jobs/5266839185.
=> Disable Go http mirroring test.

.github/workflows/ci.yaml, CHANGELOG.md, mirrord-layer/tests/apps/app_go/main.go, mirrord-layer/tests/http_mirroring.rs
Wait for all unique methods to be done once, using a wait group. Synchronize done map with a mutex so that the same http method does not report it's done twice, if e.g. two GETs are sent.
=> Make Go test stable.

Cargo.lock, mirrord-config/Cargo.toml, mirrord-config/src/agent.rs, mirrord-config/src/env.rs, mirrord-config/src/feature.rs, mirrord-config/src/fs.rs, mirrord-config/src/incoming.rs, mirrord-config/src/lib.rs, mirrord-config/src/network.rs, mirrord-config/src/outgoing.rs, mirrord-config/src/pod.rs, mirrord-config/src/util.rs
I took the liberty of implementing #538 as it took a few minutes only.
I added a test that is ignored by default that is used to generate the schema that can be submitted to schema store afterwards. I usually add the schema generation to my CLIs as well as a command but I don't ever recall actually using them.
Descriptions are generated from doc comments, so they are nonexistent, but completion and validation works:
=> feat(config): JSON schema

CHANGELOG.md, mirrord-schema.json, mirrord/config/src/lib.rs, mirrord/kube/src/api/kubernetes.rs, mirrord/kube/src/error.rs
=> mirrord-config: specify custom path for kubeconfig

CHANGELOG.md, Cargo.lock, mirrord-schema.json, mirrord/agent/Cargo.toml, mirrord/agent/Dockerfile, mirrord/agent/src/steal/connection.rs, mirrord/agent/src/steal/ip_tables.rs, mirrord/config/src/agent.rs, mirrord/config/src/lib.rs, mirrord/kube/src/api/container.rs, tests/src/traffic/steal.rs
- Issue: #1029
Adds [`conntrack --flush`](https://manpages.debian.org/testing/conntrack/conntrack.8.en.html) to the agent whenever stealer redirect rule is added.
The feature is gated behind the `flush_connections: bool` config, and the `MIRRORD_AGENT_STEALER_FLUSH_CONNECTIONS` agent env var.
=> flush after redirect with conntrack

CHANGELOG.md, mirrord/cli/Cargo.toml, mirrord/cli/src/execution.rs, mirrord/kube/src/api.rs, mirrord/kube/src/api/env_guard.rs
to prevent (self) misconfigurations (our kube settings being used from remote).
=> Added env guard to be used in cli + extension

CHANGELOG.md, mirrord/layer/src/detour.rs, mirrord/layer/src/file/filter.rs, mirrord/layer/src/socket/hooks.rs, mirrord/layer/src/socket/ops.rs, mirrord/layer/tests/bash.rs, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/sip.rs, tests/python-e2e/hostname.py, tests/src/lib.rs, tests/src/traffic.rs
gethostname detour that uses the `/host/hostname` file on the remote to get the hostname
relevant for #1041
=> mirrod-layer: gethostname detour

CHANGELOG.md, mirrord/agent/src/main.rs, mirrord/agent/src/steal/ip_tables.rs
This changes when tcp stealing on a meshed service, requests from localhost to localhost like healthprobes will skip mirrord 
and will be routed to the underlying service like when stealing from a non meshed service
Relevant for #1044
=> More consistent behavior between Mesh and Non Mesh stealing

CHANGELOG.md, mirrord/layer/src/error.rs, mirrord/layer/src/lib.rs, mirrord/layer/src/tcp_steal.rs
=> Handle the case where the local app closes a stolen TCP connection.

CHANGELOG.md, mirrord/agent/src/cli.rs, mirrord/agent/src/error.rs, mirrord/agent/src/main.rs, mirrord/config/src/agent.rs, mirrord/kube/src/api/container.rs, tests/src/lib.rs, tests/src/pause.rs
#1111.
When agent is exiting, unpause the target container if paused.
This PR also adds a test. The test runs mirrord such that the agent accepts 1 connection, pauses the target container, and then exits with an error. The test then waits for the agent job to complete and then verifies that the container is unpaused (answers an http request).
To support this test this PR adds 
1. Support for custom namespaces in E2E tests.
2. A test-error feature that enables (in debug builds) to make the agent exit early with an error.
The fix, the test, and the two test utilities are each contained in their own commit, so if you want to break down the review into smaller parts, I recommend reviewing one commit at a time.
=> Unpause on Agent Error

CHANGELOG.md, Cargo.lock, mirrord/layer/src/lib.rs, mirrord/layer/src/socket.rs, mirrord/layer/src/socket/id.rs, mirrord/layer/src/socket/ops.rs, mirrord/layer/src/tcp.rs
- Issue #1054 
Although this does not solve the issue, it's considered a welcome refactor anyway, and will (hopefully) help with #1123 , which is the bigger culprit that needs fixing.
I've left a few warnings in docs saying that you should not use the `SOCKET_ALLOCATOR` directly, would this be worth it putting into a new module (with the `SocketId` type) to prevent accidental usage?
=> Add id to UserSocket.

changelog.d/1203.added.md, mirrord/layer/src/file/hooks.rs, mirrord/layer/src/socket/hooks.rs
- Issue: #1203 
Adds `$NOCANCEL` version of functions we're hooking, to appease macos.
Also related to #947
=> Hooks for NOCANCEL functions.

changelog.d/detours.changed.md, mirrord/layer/src/common.rs, mirrord/layer/src/exec.rs, mirrord/layer/src/file/hooks.rs, mirrord/layer/src/file/ops.rs, mirrord/layer/src/socket/ops.rs
- Issue: #947 (loosely related)
Introduces a new extension trait that converts `*const c_char` into a _detoured_ Rust type, like `Detour<PathBuf>`.
=> Introduce CheckedInto trait to deal with raw pointer conversions.

Cargo.lock, changelog.d/1206.changed.md, mirrord/layer/Cargo.toml, mirrord/layer/src/file.rs, mirrord/layer/src/file/ops.rs, mirrord/layer/src/lib.rs, mirrord/layer/src/socket/ops.rs
- Issue: #1206 
Change `Mutex<HashMap>` to use `DashMap` for `OPEN_FILES`. Hoping this helps us with deadlocking woes.
=> Introduce DashMap for OPEN_FILES.

changelog.d/+operator-limits.changed.md, mirrord/operator/src/setup.rs
Add default requests and limits values to mirrord-operator setup.
Equivalent to
```yaml
...
resources:
requests:
memory: "100Mi"
cpu: "100m"
limits:
memory: "100Mi"
cpu: "100m"
```
=> mirrord-operator: Default resources limits

changelog.d/1222.fixed.md, scripts/install.sh
Add option to install specific version using the `install.sh` script via command line argument or `VERSION` environment variable
Closes #1222
=> Add option to install specific version using the `install.sh` script

changelog.d/1061.added.md, mirrord/cli/src/config.rs, mirrord/cli/src/execution.rs, mirrord/cli/src/extension.rs, mirrord/cli/src/main.rs, mirrord/layer/src/load.rs, vscode-ext/src/extension.ts
Part of #747, solves #1061.
Since we do this by changing the executable field in the launch configuration and that field is different in each configuration type we need to add specify the configuration type -> configuration field name for each configuration type we want to support, currently supporting node and python.
=> Add SIP sidestepping to the vs-code extension, with support from the cli extension command.

DEBUGGING.md, TESTING.md, changelog.d/+dev-docs.internal.md
Update some outdated stuff like the commands for building the agent, or the layer on macOS.
Add instructions for the IDE extensions.
=> Update dev docs.

changelog.d/+random_crash_fix.fixed.md, mirrord/layer/src/lib.rs
caused by supposed closing of stdout/stderr then calling to log that writes to it
=> Fixed random crash in `close_layer_fd`

changelog.d/1266.added.md, vscode-ext/src/extension.ts
Solves #1266 
When there is no target specified in the mirrord configuration file and there is no available target in the current namespace, an error prompt is shown to the user and debugging session is cancelled.
See in action [here](https://user-images.githubusercontent.com/34063647/230900208-bf32030b-94f0-4f6a-a559-de6e5627c73a.webm)
=> Error message displayed in VS Code when there is no selectable target

changelog.d/+default_subscriptions.internal.md, mirrord/agent/src/sniffer.rs, mirrord/agent/src/util.rs
According to `todo` left by @meowjesty 
Removed `Subscriptions::new` method and implemented `Default` trait.
=> Implemented `Default` for `Subscriptions` struct

changelog.d/1163.added.md, mirrord/agent/src/dns.rs, mirrord/agent/src/error.rs, mirrord/agent/src/main.rs, mirrord/agent/src/outgoing.rs, mirrord/agent/src/outgoing/udp.rs, mirrord/agent/src/sniffer.rs, mirrord/agent/src/steal/api.rs, mirrord/agent/src/steal/connection.rs, mirrord/agent/src/util.rs, mirrord/agent/src/watched_task.rs, mirrord/layer/src/lib.rs, mirrord/protocol/src/codec.rs
Solves #1163.
1. Changed `protocol::codec::LogMessage` to allow sending logs on `warn`/`error` level from agent to layer.
2. Added `WatchedTask` and `TaskStatus` helper structs to capture errors from agent's background tasks and access them from different contexts.
3. Wrapped all agent's background tasks with those structs. Implemented returning errors to clients using tasks' APIs (`DnsApi`, `TcpStealerApi`, ...).
1. `DaemonMessage::LogMessage` is propably not very useful. In all cases we stop serving the client after the first error, so using the existing `DaemonMessage::Close` was sufficient. I use `DaemonMessage::LogMessage` in just one case - when we can't create the API for the sniffer. Should I leave it as is or remove that variant completely?
2. I removed casting all errors to …
=> Propagate steal issues

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, changelog.d/1051.internal.md, mirrord/layer/tests/apps/outgoing/Cargo.toml, mirrord/layer/tests/apps/outgoing/src/main.rs, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/outgoing.rs
Fixes #1051 
Udp test fails for now, remote address returned from `recv_from` is some localhost port.
=> Integration tests for outgoing UDP/TCP

changelog.d/1155.changed.md, mirrord/sip/src/error.rs, mirrord/sip/src/lib.rs
#1155 
Up until now we only used x86_64 binaries for SIP-patched binaries.
This means that if a binary did not have a x64 binary in it, we couldn't patch it.
Now, we can also patch it if there is an arm64 binary (when running on apple chips). Also, if both x86_64 and arm64 are present, we use arm64 (when running on apple chips), and avoid running over rosetta.
=> Use arm64 if there in SIP patching

changelog.d/1267.added.md, intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt, intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordExecManager.kt
Fixes #1267
I changed the error notification for the case when no target is available. Now the message matches the one we show in the VS Code extension and suggests changing the namespace or kubeconfig.
By the way, I noticed that a failure of `mirrord ls` was not handled and resulted with a null pointer exception. Added an error prompt and a log of stderr.
[See in action here](https://user-images.githubusercontent.com/34063647/232569283-d7895a63-fa56-4491-b320-5843f5548f71.webm)
=> Improve target selection in IntelliJ extension

TESTING.md, changelog.d/+fix-build-instructions.internal.md
Building the project now requires a protoc installed (due to `k8s-cri` dependency in the agent)
=> Added protoc dependency to the build instructions

changelog.d/1348.added.md, vscode-ext/src/extension.ts
Resolves #1348
The first entry in target selection list is now the last used target. The rest of the list is sorted.
=> Last selected target prioritized in VS Code

changelog.d/1364.fixed.md, intellij-ext/modules/products/goland/src/main/kotlin/com/metalbear/mirrord/products/goland/GolandRunConfigurationExtension.kt
=> Fixed delve patch not working on GoLand macOS when running go tests

changelog.d/1020.fixed.md, intellij-ext/build.gradle.kts, intellij-ext/modules/products/pycharm/src/main/kotlin/com/metalbear/mirrord/products/pycharm/PythonCommandLineProvider.kt, intellij-ext/modules/products/pycharm/src/main/kotlin/com/metalbear/mirrord/products/pycharm/PythonRunConfigurationExtension.kt, mirrord/layer/src/debugger_ports.rs
Fixes #1020 
Added new `DebuggerType` variant for PyDevD used by PyCharm.
Also fixed `:runIde` command for PyCharm Community and Ultimate
=> Detect Python debugger PyCharm

changelog.d/1337.changed.md, intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt, intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordExecManager.kt, intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordNotifier.kt
closes #1337
the above-mentioned issue mentions "mirrord started!" is never displayed, this happened because of the underlying implementation of the Signleton notifier being used as it did not display the notification if a bubble had not expired. To fix this we use the ProgressManager API, however we still don't usually see "mirrord started!" because it happens too fast.
some considerations while making this change:
- 
```
/**
* Runs the given process synchronously in calling thread, associating this thread with the specified progress indicator.
* This means that it'll be returned by {@link ProgressManager#getProgressIndicator()} inside the {@code process},
* and {@link ProgressManager#checkCanceled()} will throw a {@link ProcessCanceledException} if the progress indicator is canceled.
* …
```
=> Display mirrord loading progress in the status bar

CHANGELOG.md, mirrord/layer/src/file/filter.rs
tweaked locals overrides to have `/private` `/tmp` and removes `.*$` from the pattern to include directory listing as well
Partially solves #1397
=> Fixed `go run` failing because of reading remote files 

changelog.d/+invalid-target-msg.changed.md, mirrord/config/src/target.rs
Current message output was:
```
"Provided target: \"ip-visit-counter-6cf56d9ddf-bqjp8\" is neither a pod or a deployment. Did you mean pod/\"ip-visit-counter-6cf56d9ddf-bqjp8\" or deployment/\"ip-visit-counter-6cf56d9ddf-bqjp8\"\n\nmirrord-laye
```
might make users thing they need quotes after the type (pod/deployment)
=> Remove quotes in InvalidTarget' target error message

changelog.d/+towncrier.fixed.md, changelog.d/1030.added.md, intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordConfigDropDown.kt
Problem: query the index while it is being built is bad
Solution:
If there is an update available, spawn a task that queries the index while blocking new tasks from being started so there is only one task in case there is an update available
=> Prevent a possible race condition on config dropdown

changelog.d/+towncrier.fixed.md, intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordConfigDropDown.kt
Fix:
```
mirrord 3.42.0 is binary incompatible with IntelliJ IDEA Ultimate IU-222.4554.10 due to the following problem
Abstract method is not implemented (1 problem)
Abstract method ComboBoxAction.createPopupActionGroup(JComponent) is not implemented (1 problem)
```
=> Fix intelliJ compatibility error

.github/workflows/ci.yaml, changelog.d/574.added.md, mirrord/cli/src/config.rs, mirrord/cli/src/connection.rs, mirrord/cli/src/error.rs, mirrord/cli/src/execution.rs, mirrord/cli/src/main.rs, mirrord/config/src/config.rs, mirrord/config/src/lib.rs, mirrord/config/src/target.rs, mirrord/kube/src/api.rs, mirrord/kube/src/api/container.rs, mirrord/kube/src/api/kubernetes.rs, mirrord/kube/src/error.rs, mirrord/layer/src/detour.rs, mirrord/layer/src/lib.rs, mirrord/layer/src/socket/ops.rs, mirrord/operator/src/client.rs, mirrord/operator/src/crd.rs, tests/src/env.rs, tests/src/file_ops.rs, tests/src/lib.rs, tests/src/pause.rs, tests/src/targetless.rs, tests/src/traffic.rs
#574.
When not specifying any target, a targetless agent is spawned, which is independent of any other pod.
=> Support targetless agents.

changelog.d/1375.added.md, intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordApi.kt, intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordExecDialog.kt, intellij-ext/modules/core/src/main/kotlin/com/metalbear/mirrord/MirrordExecManager.kt
#1375 
Allow null targets in the intelliJ plugin, notify about targetless runs.
To run targetless the user can choose the targetless target (or no target).
If the user presses `cancel` or closes the dialog, we cancel the loading of mirrord.
=> Targetless intellij

changelog.d/574.added.md, mirrord/config/src/target.rs, mirrord/kube/src/api/container.rs
In the unreleased targetless PR I broke the target config because I misunderstood when the `Simple` and `Advanced` variants are generated. This PR fixes that.
=> Fix broken target config.

Cargo.lock, changelog.d/1408.added.md, mirrord-schema.json, mirrord/agent/src/container_handle.rs, mirrord/agent/src/error.rs, mirrord/agent/src/main.rs, mirrord/cli/src/error.rs, mirrord/cli/src/execution.rs, mirrord/cli/src/main.rs, mirrord/config/src/agent.rs, mirrord/config/src/lib.rs, mirrord/kube/src/api/container.rs, mirrord/layer/src/lib.rs, mirrord/protocol/src/codec.rs, mirrord/protocol/src/lib.rs, mirrord/protocol/src/pause.rs
Resolves #1408 
Clients can now dynamically request the agent to pause the remote container. This is done with a new message, which is sent only once (by the CLI, right after fetching the remote env). The remote container remains paused by the agent until exit or an unpause request has been received (this case will be handled in the operator).
The flag controlling the pause feature is moved from `AgentConfig` to `LayerConfig` and is still accessible through `MIRRORD_PAUSE` env variable.
=> Dynamic target pause

changelog.d/1436.changed.md, mirrord/cli/src/main.rs
Closes #1436 
(not crashing,starting,etc)
=> Change mirrord ls to show only pods that are in running state 

changelog.d/+lowercase-progress.changed.md, mirrord/cli/src/connection.rs, mirrord/cli/src/operator.rs, mirrord/operator/src/client.rs
Most of the progress statuses and task names are lowercase so it doesn't look very good when just one line is capitalized, so this PR makes all of the task names and statuses lowercase, so that instead of:
```
⠸ mirrord cli starting
✓ ready to launch process
✓ layer extracted
✓ No Operator Detected       # <---- only this is capitalized.
✓ agent pod created
✓ pod is ready
```
we get
```
⠼ mirrord cli starting
✓ ready to launch process
✓ layer extracted
✓ no operator detected
✓ agent pod created
✓ pod is ready
```
Sending this PR now because I want to include a screenshot in a blogpost and I want it to look nice :)
=> Make progress text consistently lowercase.

changelog.d/+fix-strip-test.internal.md, mirrord/layer/tests/fileops.rs
This test tests our logic that makes file operations in our SIP-patch dir happen locally, and outside of that dir.
So if there is a read from /tmp/mirrord-bin/usr/lib/whatever, it should happen locally, but to /usr/lib/whatever.
The way the test verifies this is by writing some content to /tmp/whatever, then running `mirrord exec cat /tmp/mirrord-bin/tmp/whatever` and verifying it reads what it wrote.
However due to a bug in the test it was not reading directly from where it wrote.
This PR fixes this test bug and also adds an check that the read path is not the same as the write one.
=> fix strip test

.github/workflows/ci.yaml, changelog.d/1453.internal.md
Solves #1453
I looked into the tests and the code around, couldn't find any exact reason for the tests to behave badly. Also, tests are failing only if too many of them are being run at the same time. I assume it is simply too much load for minikube. Even when the runtime is given 32 cores, running all 71 tests at once causes some to fail.
With concurrency now limited to 5 tests at the same time, the suite passes without problems.
=> Unflaking e2e tests

changelog.d/+index-allocator-improvement.internal.md, mirrord/agent/src/file.rs, mirrord/agent/src/main.rs, mirrord/agent/src/outgoing.rs, mirrord/agent/src/outgoing/udp.rs, mirrord/agent/src/sniffer.rs, mirrord/agent/src/steal/connection.rs, mirrord/agent/src/util.rs, mirrord/layer/tests/common/mod.rs, tests/src/lib.rs, tests/src/traffic/steal.rs
Provide buffer for `IndexAllocator` to avoid re-use of indices too fast
=> Fix possible race with `IndexAllocator`

changelog.d/+ignore-gcc-for-go-vsc.fixed.md, vscode-ext/src/extension.ts
When investigating user's issues in Go + VSCode setup I noticed that layer gets loaded into a `gcc` process spawned with `gcc -### -x c -c -`. Probably not what we want
=> Skip `gcc` - debugging Go with VSCode extension

changelog.d/+bump-vscode-ext-deps.internal.md, vscode-ext/package-lock.json
`npm install` no longer warns about critical vulnerabilities :)
=> Bumped dependencies in the VS Code extension

Cargo.lock, Cargo.toml, changelog.d/+socket2.internal.md
In https://github.com/rust-lang/socket2/pull/403, we added some code to `socket2`, for https://github.com/metalbear-co/mirrord/issues/1105. Up until now the dependency was on my `socket2` fork, but a version that includes those changes was released already, so we can depend on the new version of the official crate again.
=> Update socket2 dependency

.github/workflows/ci.yaml, Cargo.lock, changelog.d/1355.internal.md, mirrord/agent/Dockerfile, mirrord/layer/src/file.rs, mirrord/macros/Cargo.toml, mirrord/macros/src/lib.rs, mirrord/protocol/Cargo.toml, mirrord/protocol/src/codec.rs, mirrord/protocol/src/file.rs, mirrord/protocol/src/tcp.rs
change `mirrord-protocol` to have its own versioning. add `mirrord-macros` and `protocol_break` attribute to mark places we want to break on major updates.
Add CI to verify that if protocol is changed, `Cargo.toml` is changed as well (to force bumps)
Fix some of the structs being `OS` controlled, potentially breaking the protocol between different OS's. (`GetDEnts64(RemoteResult<GetDEnts64Response>),`)
Closes #1355
=> Many protocol adjustments

changelog.d/+frida-fast-replace.internal.md, mirrord/layer/src/hooks.rs
This reverts commit 2f656622b06fcdc0fa6f73ad6f1b279cc5552ed5.
this messes up c# debugger.
=> Revert "use replace fast with frida (#1536)"

.github/workflows/ci.yaml, changelog.d/+vscode-ci-fix.internal.md
looks like the vscode e2e job doesnt run, since build_mirrord and test_agent_image dont see the fs change and it makes the e2e skip
=> Fix vscode e2e job not running

changelog.d/1570.changed.md, changelog.d/1570.fixed.md, mirrord/layer/src/file/filter.rs
Prevents #1570 from happening and enables using mirrord for running python on mac, but does not solve the underlying problem with Rust/Tokio/Frida/our SIP sidestepping.
=> make python run on apple.

Cargo.lock, changelog.d/1530.fixed.md, mirrord/agent/src/steal/connection.rs, mirrord/layer/src/error.rs, mirrord/layer/src/lib.rs, mirrord/layer/src/socket.rs, mirrord/layer/src/tcp.rs, mirrord/layer/src/tcp_mirror.rs, mirrord/layer/src/tcp_steal.rs, mirrord/layer/tests/self_connect.rs, mirrord/protocol/Cargo.toml, mirrord/protocol/src/outgoing.rs, tests/python-e2e/close_socket.py, tests/python-e2e/close_socket_keep_connection.py, tests/src/lib.rs, tests/src/traffic/steal.rs
closes #1530.
When `close()` is called, if it's a socket managed by mirrord - notify the TcpHandler (mirror/steal) via `HookMessage`, which removes the port from the listen set, and sends a `PortUnsubscribe` to the agent.
The agent side's handling was already implemented.
=> Handle user app closing a socket

changelog.d/+e2e-tests-improved.internal.md, tests/src/lib.rs
Resource deletion now blocks 1 runtime thread - when dropped, `ResourceGuard` spawns another OS thread and runs the deletion logic in a separate single-threaded runtime.
Optimization - `KubeService` holds 3 resource guards, so it runs their deletions in one runtime when dropped.
=> e2e tests - fixed resource deletion blocking 2 runtime threads

README.md, changelog.d/1615.changed.md, mirrord/kube/src/api/container.rs
Solves #1615 
I found that `CAP_NET_ADMIN`, `CAP_SYS_PTRACE` and `CAP_SYS_ADMIN` is a minimal set allowing the agent to function. E2E tests pass and removing any of these capabilities causes them to fail.
* `CAP_NET_ADMIN` - modifying ip tables
* `CAP_SYS_PTRACE` - reading `/proc/<target>/environ`
* `CAP_SYS_ADMIN` - entering target's network namespace
Sadly, `CAP_SYS_ADMIN` is a very broad capability. AFAIK it is used by kernel developers too often. Quote from "Note to developers": "It can plausibly be called the new root"
=> Run agent as a non-privileged container

.github/workflows/ci.yaml, changelog.d/1459.fixed.md, mirrord/layer/src/exec_utils.rs, mirrord/layer/src/file/hooks.rs, mirrord/layer/tests/apps/java_temurin_sip/.gitignore, mirrord/layer/tests/apps/java_temurin_sip/src/Main.java, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/java_sip.rs, mirrord/sip/src/error.rs, mirrord/sip/src/lib.rs, mirrord/sip/src/rpath.rs, scripts/install_test_app_frameworks.sh
closes #1459.
1. Adding a test that verify that java from that specific distribution can start with mirrord (the process couldn't even start before).
2. The problem was the binary had `rpath` loader commands with `@loader_path`, and dependencies that are in `rpath`, so the loader was looking for paths that are relative to the patched binary, and did not find them. So we now add an `rpath` entry to `@loader_path` or `@executalbe_path` with the path of the original binary instead.
3. Also, the binary was calling `dlopen` on a path that's inside our patch dir, so we're adding a hook for `dlopen` with the standard path stripping.
4. The `open$NOCANCEL` hook was replacing the wrong symbol.
I recommend reviewing this PR one commit at a time.
=> Fix running java 17.0.6-tem with mirrord on macOS

changelog.d/+consistent-fs-mode.internal.md, mirrord/layer/src/lib.rs
We override the fs mode on targetless to be `localwithoverrides` regardless of user config.
However, it was only being done for the `FILE_FILTER` global. This PR changes it to be consistent everywhere (also in `FILE_MODE` and in the config object passed to the layer task).
=> Have the same fs-mode everywhere.

Cargo.lock, changelog.d/+medschool-better-ux.internal.md, medschool/Cargo.toml, medschool/readme.md, medschool/src/main.rs
- Issue: n/a
Adds a few args when running `medschool`:
- `--prepend`: prepends a file to the generated markdown;
- `--input`: now you can specify the folder to run `medschool` in (previously you had to `cd` into the `src` dir you wanted);
- `--output`: you can now specify a path (and filename) where the markdown will go (previously it was just current dir);
=> medschool now supports args to make it easier to run.

changelog.d/1641.fixed.md, mirrord/layer/src/debugger_ports.rs
=> Pass detected debugger port down to the children processes

changelog.d/+dynamic-pause-operator.fixed.md, changelog.d/+fix-timeout-on-proxy.fixed.md, mirrord/cli/src/error.rs, mirrord/cli/src/execution.rs, mirrord/cli/src/internal_proxy.rs, mirrord/kube/src/api.rs, mirrord/layer/src/error.rs, mirrord/layer/src/lib.rs
- moved pause request to be from internal proxy
- Fixed case where proxy can timeout since it holds a stale connection. Added heartbeat to the connection handling
=> Fixed dynamic pause with operator not working

changelog.d/1695.changed.md, mirrord/agent/src/env.rs
Added env var exclusion for `_JAVA_OPTIONS` to avoid loading remote jars or settings that wouldn't work locally.
Closes #1695
=> Added env var exclusion for `_JAVA_OPTIONS` 

changelog.d/+toleration-docs-json.fixed.md, mirrord-schema.json, mirrord/config/src/agent.rs
All other configuratiuon values are documented as json, and the extensions only support json, I think.
See https://github.com/metalbear-co/mirrord.dev/pull/118#discussion_r1271320138
=> Change tolerations default value documentation to json

changelog.d/1752.fixed.md, mirrord/config/src/util.rs, mirrord/layer/src/debugger_ports.rs, mirrord/layer/src/lib.rs, mirrord/layer/src/load.rs, mirrord/layer/tests/apps/open_file/open_file.c, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/skipping_process.rs, scripts/build_c_apps.sh
Closes #1725 
Using mirrord with a go project was failing even without the devcontainer, because the layer was injecting into common build tools like `gcc` or `ld`. This is a regression introduced recently.
Layer now inspects both path to the executable name and the process arguments when determining load type.
=> Fix detecting skipped processes

changelog.d/+no-message-on-old-operator.changed.md, mirrord/operator/src/client.rs
Change operator / cli version mismatch to show only when mirrord is older than operator
=> Change operator / cli version mismatch warning

changelog.d/1761.added.md, mirrord-schema.json, mirrord/cli/src/config.rs, mirrord/cli/src/execution.rs, mirrord/cli/src/extension.rs, mirrord/cli/src/internal_proxy.rs, mirrord/cli/src/main.rs, mirrord/config/src/internal_proxy.rs, mirrord/config/src/lib.rs
Added `internal_proxy` timeout configurations to allow users specify timeouts in edge cases.
=> Added `internal_proxy` timeout configurations to allow users specify timeouts

changelog.d/1747.fixed.md, mirrord/layer/src/file/hooks.rs
Add missing hook for `read$NOCANCEL`, fixes reading remote files in some scenarios.
=> Add missing hook for `read$NOCANCEL`

changelog.d/+default-json-progress-ext.fixed.md, mirrord/cli/src/extension.rs, mirrord/progress/src/lib.rs
This is a regression in `mirrord cli`. IntelliJ extension does not set `MIRRORD_PROGRESS_MODE`.
=> Using json progress tracker as default in extension

changelog.d/1809.fixed.md, mirrord/agent/src/dns.rs
closes #1809 
Just converted other errors to be DnsLookup errors so we always send ResponseError::DnsLookup as an error
=> `ResponseError::DnsLookup` for errors during DNS lookup

changelog.d/1828.fixed.md, mirrord/layer/src/socket/hooks.rs, mirrord/layer/src/socket/ops.rs
Fixed wrong errno being set by mirrord fixing various flows that rely on errno even when return code is ok
Closes #1828
=> Fixed wrong errno being set by mirrord

changelog.d/1694.fixed.md, mirrord-schema.json, mirrord/config/src/feature/fs.rs, mirrord/config/src/feature/fs/advanced.rs, mirrord/config/src/feature/fs/mode.rs, mirrord/layer/src/error.rs, mirrord/layer/src/file/filter.rs, mirrord/layer/src/lib.rs
Closes #1694 
I passed on resolving the `~`, as it's already handled by regexes. Open to suggestions.
~~Also, there is a conflict between our default `remote-readonly` and `not-found` filters. The default `remote-readonly` filter matches paths `\.aws/cli/cache/.+\.json$`, `\.aws/credentials$` and `\.aws/config$`. Not sure how to deal with this. An ideal solution would be to have a list of `(pattern, logic)` entries and stop at the first one matching, but this is not backwards-compatible~~
=> `not-found` file filter

changelog.d/+config-verify-aggregated.changed.md, mirrord/cli/src/execution.rs, mirrord/config/src/lib.rs
Changed config verify to return aggregated warnings list for user to print instead of warn in current progress - can fix issues with extension where we printed to stderr.
Might fix issues where config is wrong and weird message will be seen in extension (since it sends it to stderr)
=> Changed config verify to return aggregated warnings 

.github/workflows/ci.yaml, .github/workflows/release.yaml, changelog.d/+ci-improvements-faster.internal.md, changelog.d/+macos-sip.fixed.md, mirrord/layer/tests/bash.rs, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/configs/bash_script.json, mirrord/sip/src/codesign.rs
- use Go cache for integration tests
- Fix macOS SIP potential issues from exec having mirrord loaded into the code sign binary.
- use mac-13 runner for tests
=> Faster CI + SIP issue

.github/workflows/ci.yaml, changelog.d/+ci-improvements-more2.internal.md, tests/rust-e2e-fileops/src/main.rs
Reorganize the CI with the following objective of unifying as much as we can CI that can run on the same host, this is to have less caches and have better compilation time (as there's overlap). Things done:
- Remove the build layer CI, since we now have an integration tests that check it + clippy for aarch darwin / Linux
- Make clippy run for all of the project for aarch64 linux instead of agent only
- Revert removal of Rust cache from e2e (was by mistake)
- Don't use "cache" for other Gos since it will try to overwrite and have bad results.
- Added some docs on CI.
=> More CI improvements

changelog.d/+open-shift-detect.fixed.md, mirrord/kube/src/api/kubernetes.rs
Fix openshift detection taking too long by querying a subset instead of all APIs
=> Fix openshift detection taking too long by querying a subset 

.github/workflows/ci.yaml, changelog.d/+ci-improvements-macos.internal.md, tests/node-e2e/http2/test_http2_traffic_steal.mjs
Unify lint and integration for macOS to save cache and runner. Remove trace logging from integration tests on macos
=> macOS CI improvements

Cargo.lock, changelog.d/1872.fixed.md, mirrord/analytics/Cargo.toml, mirrord/analytics/src/lib.rs
Fixed panic on crash analytics by using tokio::spawn instead of blocking in a drop that is in a Tokio context
Closes #1872
=> Fixed panic on crash analytics

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, changelog.d/1899.added.md, mirrord/layer/src/file/hooks.rs, mirrord/layer/tests/apps/issue1899/Cargo.toml, mirrord/layer/tests/apps/issue1899/src/main.rs, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/issue1899.rs
- Issue: #1899
Add hook for `opendir` by leveraging our `open` and `fdopendir` hooks.
Also adds hooks for `readdir64_r`, `__lxstat`, `__lxstat64`, `__xstat64`.
Refactors `*stat` hooks to use a common function.
Adds an integration test for `opendir`.
=> Add hook for opendir, issue #1899

changelog.d/1920.fixed.md, mirrord/layer/src/file/hooks.rs
Disable opendir hook on aarch macOS since it crashes due to arm64e issues
Closes #1920
=> Disable opendir hook on aarch macOS 

changelog.d/1840.fixed.md, mirrord/cli/src/main.rs
- Issue: #1840
`mirrord verify-config [path]` command would not produce a correct serialized JSON due to an issue coming from `serde` ((this)[https://github.com/serde-rs/serde/issues/1307]).
=> Fix verify-config command when used with invalid `config.json`.

changelog.d/1968.changed.md, mirrord/layer/src/file/filter.rs
Changed file filter to exclude jar files from being read remote by default
Closes #1968
=> Changed file filter to exclude jar files from being read remote by default

changelog.d/1967.fixed.md, mirrord/layer/src/file/hooks.rs
=> Call `FN_STAT`, not `FN_LSTAT` from `stat` bypass

Cargo.lock, changelog.d/1963.fixed.md, mirrord/agent/src/cli.rs, mirrord/agent/src/main.rs, mirrord/agent/src/sniffer.rs, mirrord/agent/src/steal/ip_tables.rs, mirrord/agent/src/steal/ip_tables/mesh.rs, mirrord/kube/src/api/container.rs, mirrord/kube/src/api/container/ephemeral.rs, mirrord/kube/src/api/container/job.rs, mirrord/kube/src/api/kubernetes.rs, mirrord/kube/src/api/runtime.rs, mirrord/protocol/Cargo.toml, mirrord/protocol/src/error.rs, mirrord/protocol/src/lib.rs
- Issue: #1963
Moved `MeshVendor` from the agent crate to the protocol crate, as it's now being used by both kube and agent. The previous implementation stuff we had in `steal/iptables` for it is still there, as an extension trait.
Instead of just detecting that we're in a mesh (kube crate), we now propagate the type of mesh to the agent through the `--mesh` arg, and if it's `istio`, sniffer captures traffic on `lo`, instead of `eth0` (steal should be unaffected by this change).
=> Make mirror (in mesh) capture on the lo interface, instead of eth0 (or equivalent) by default (user setting takes priority).

changelog.d/1979.fixed.md, mirrord/cli/src/config.rs, mirrord/cli/src/extension.rs, mirrord/cli/src/main.rs, mirrord/cli/src/verify_config.rs, mirrord/config/src/config.rs, mirrord/config/src/lib.rs
- Issue: #1979 
Adds the optional `--ide` flag to `mirrord verify-config [--ide] --path {/config/path}`.
Creates a special case for `config::verify` where we may turn some errors (target related) to warnings when we're in an IDE context, as the user may select a target instead of putting on in the config file.
=> Add --ide flag to verify-config, changing some errors into warnings.

STYLE.md, changelog.d/+style_example.internal.md
Alternatively, we can change the rule to say `..._sender` and `..._receiver`. The point of the PR is to have the example and the rule agree with each other.
=> Make example conform to its rule in style guide

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, changelog.d/2001.fixed.md, mirrord/layer/src/file.rs, mirrord/layer/src/file/hooks.rs, mirrord/layer/src/file/open_dirs.rs, mirrord/layer/src/file/ops.rs, mirrord/layer/tests/apps/issue2001/Cargo.toml, mirrord/layer/tests/apps/issue2001/src/main.rs, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/issue2001.rs
Closes #2001 
User application was crashing, because while opening the directory was hooked, `readdir64` - used by JVM - was not. libc was getting our opaque identifier as a pointer to `DIR` and segfaulting.
=> Missing `readdir` and `readdir64` detours

changelog.d/2019.internal.md, mirrord/layer/src/file/filter.rs, mirrord/layer/src/file/filter/not_found_by_default.rs, mirrord/layer/src/file/filter/read_local_by_default.rs, mirrord/layer/src/file/filter/read_remote_by_default.rs
Closes #2019
Many users have difficulty using mirrord because they expect all files to be read remotely by default, and their application is trying to read a file that is in our set of exceptions to that rule. We should make it clearer to users that those exceptions exist and make it easier for them to see what they are (many users ask for that).
Having the list of exceptions on the website would be good reader experience, but that would be prone to become outdated, so I think a good compromise is to put those lists alone in their own files, and then link to those files from the documentation/FAQ/wherever.
What do you think?
=> Put exception path patterns in their own files so that we can link to them

Cargo.lock, Cargo.toml, changelog.d/+kubectl-auth-plugin.fixed.md
Switched `kube` dependency to [new branch](https://github.com/Razz4780/kube/tree/fixes), including both `socks5` proxy support and fix for authentication plugins
=> Update kube dep

changelog.d/+mirrord-console-fix.fixed.md, mirrord/console/src/async_logger.rs
Intproxy fails to send logs to `mirrord-console`, producing following output:
```
razz4780@razz4780-machine:~/MetalBear/mirrord$ ./target/debug/mirrord exec -t pod/py-serv-deployment-5fffb9767c-nvl88 --fs-mode=local -- x-terminal-emulator
⠄ mirrord exec
✓ Running on latest (3.74.0)!
✓ ready to launch process
✓ layer extracted
✓ no operator detected
✓ agent pod created
✓ pod is ready                                                                                                                                                                                  razz4780@razz4780-machine:~/MetalBear/mirrord$ ./target/debug/mirrord exec -t pod/py-serv-deployment-5fffb9767c-nvl88 --fs-mode=local -- terminator
⠠ mirrord exec
✓ Running on latest (3.74.0)!
✓ ready to launch process
✓ layer extracted …
```
=> Mirrord console fix

changelog.d/2047.fixed.md, mirrord/layer/src/lib.rs
Don't drop mutex in child on fork_detour, fixes bug with elixir. Closes #2047.
=> Don't drop mutex in child on fork_detour, fixes bug with elixir

changelog.d/2055.fixed.md, mirrord/layer/src/lib.rs, mirrord/layer/src/socket/hooks.rs, mirrord/layer/src/socket/ops.rs, mirrord/layer/tests/apps/gethostbyname/gethostbyname.c, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/issue2055.rs
- Issue: #2055 
Adds a hook for [`gethostbyname`](https://www.man7.org/linux/man-pages/man3/gethostbyname.3.html) (yeah it's deprecated).
@aviramha found out that erlang/elixir uses this when resolving DNS.
There is a potential UB in how we cast some pointers that should be `*mut _` from `*const _`, but the manual of the function says that you should do a deep copy of the `*mut hostent` pointer we pass back to the user, so this shouldn't be a problem.
=> Hook gethosbyname to resolve DNS for erlang/elixir.

changelog.d/2078.fixed.md, mirrord/intproxy/protocol/src/lib.rs, mirrord/intproxy/src/lib.rs, mirrord/intproxy/src/proxies/incoming.rs, mirrord/intproxy/src/proxies/incoming/subscriptions.rs, mirrord/intproxy/src/remote_resources.rs, mirrord/layer/src/socket.rs
Closes #2078 
Before layer tokio removal PR, TCP subscription failure always terminated user's app. As part of the refactor I changed this behavior to returning regular errors from the `listen` hook. Given the problem described in issue description (intproxy receives multiple responses to a single subscription request) and that most of the time `mirrord_protocol::error::ResponseError` cannot be tracked back to the subscription request, this PR partially restores the previous behavior:
1. Layer makes a subscription request to intproxy.
2. Intproxy makes a subscription request to the agent/s.
3. Intproxy receives the first subscription result. It is either `Ok(port)`, `Err(PortAlreadyStolen(port))` or `Err(some_other_error)`. The first two variants trigger a response to the layer. The last …
=> Fix incoming TCP with multiple pods

changelog.d/+use_proxy.added.md, mirrord-schema.json, mirrord/agent/src/steal/connection.rs, mirrord/cli/src/execution.rs, mirrord/config/src/lib.rs
Added new configuration 'use_proxy' that lets user disable usage of http/s proxy by mirrord even when env is set.
=> Added new configuration 'use_proxy'

changelog.d/+targetless-verify-config.fixed.md, mirrord/cli/src/main.rs, mirrord/cli/src/verify_config.rs, mirrord/config/src/lib.rs, mirrord/config/src/target.rs
`targetless` target now serialized into the string `"targetless"` instead of `null`. This allows the IDEs to tell difference between a config with unset target and a config with target set to `targetless`
=> Fixed `mirrord verify-config` output

changelog.d/2049.fixed.md, mirrord/cli/src/connection.rs, mirrord/cli/src/error.rs, mirrord/cli/src/operator.rs, mirrord/operator/src/client.rs
Closes #2049 
1. CLI now aborts the execution if the operator is successfully detected, but using it's API failed. Previously the CLI was simply continuing the execution without the operator. However, this may lead to various errors and be confusing to the users. When aborting execution in this case, the CLI prints an informative diagnostic message (see `CliError::OperatorConnectionFailed`).
2. Error handling needs further improvement on the operator side, because errors returned from the operator API seem to be malformed. E.g. when the user specifies a non-existent target, `kube` crate returns a very ugly `ErrorResponse` struct:
```
STATUS: 500 Internal Server Error
REASON: Failed to parse error data
CODE: 500
MESSAGE: "ApiError: pods \"py-serv-deployment-5fffb9767c-vwwglxd\" not found: …
```
=> Improve handling of operator-related errors

changelog.d/+fix-verification.fixed.md, mirrord/config/src/config.rs, mirrord/config/src/lib.rs
Very small change - handled the same way as other potential errors related to `target` (see logic above in the same function)
Closes https://github.com/metalbear-co/mirrord-intellij/issues/208
Closes https://github.com/metalbear-co/mirrord-vscode/issues/85
=> Fixed config verification in IDEs with 'copy_target' feature

changelog.d/+operator-bogus-errors.fixed.md, mirrord-schema.json, mirrord/cli/src/connection.rs, mirrord/config/src/lib.rs, mirrord/operator/src/client.rs
`LayerConfig::operator` is now an `Option` - if the user is not explicit about the operator, try to use it but don't fail on errors that may occur when the operator is not installed
=> Make operator config optional

changelog.d/2101.fixed.md, mirrord/layer/src/lib.rs, mirrord/layer/src/load.rs
Closes #2101 
The layer now initializes a new session with the internal proxy with every load (full, skipped, sip-only).
This could be further optimized by leaking the TCP socket descriptor across execs (no default CLOEXEC) and making the connection only once (storing the flag in env). However, the assumption that processes wouldn't close this descriptor brings us back to the first proposed solution. Not sure about it
=> Fix intproxy timeouts with lengthy build tools

changelog.d/2115.fixed.md, mirrord/cli/src/connection.rs, mirrord/cli/src/operator.rs, mirrord/operator/src/client.rs
Closes #2115 
What it looks like when the operator is not installed:
```
⠤ mirrord exec
✓ Running on latest (3.78.0)!
✓ ready to launch process
✓ layer extracted
✓ agent pod created
✓ pod is ready 
```
```
x mirrord exec
✓ Running on latest (3.78.0)!
x preparing to launch process
✓ layer extracted
x checking operator
Error:   × Failed to connect to the operator, probably due to RBAC: finding operator failed: ApiError: "404 page not found\n": Failed to parse error data (ErrorResponse { status: "404 Not Found",
│ message: "\"404 page not found\\n\"", reason: "Failed to parse error data", code: 404 })
help: 
Please check the following:
1. The operator is running and the logs are not showing any errors.
2. You have sufficient permissions to port forward to the operator.
If you want to run …
```
=> Remove confusing operator error (when user does not specify `config.operator`)

changelog.d/2117.fixed.md, mirrord/layer/src/socket/ops.rs
Support binding [::] by resolving to ipv4 unspecified.
Fix gRPC Python running in Docker
Closes #2117
=> Support binding [::] by resolving to ipv4 unspecified

Cargo.lock, changelog.d/2099.fixed.md, mirrord/layer/Cargo.toml, mirrord/layer/src/file/hooks.rs, mirrord/layer/src/file/ops.rs, mirrord/layer/src/go/linux_aarch64.rs, mirrord/layer/src/go/linux_x64.rs, mirrord/layer/src/go/mod.rs
- Issue: #2099
Does not solve the issue itself, instead this allow mirrord to work with a boltdb app when the db file is bypassed.
Uses the [`syscalls`](https://docs.rs/syscalls/latest/syscalls/) crate to handle calling the syscalls for go.
Adds `pwrite64`, `pread64`, `fsync` and `fdatasync` hooks for go; found these out while testing a boltdb app with mirrord.
```go
package main
import (
"C"
bolt "go.etcd.io/bbolt"
)
func main() {
db, err := bolt.Open("/tmp/mirrord.db", 0600, nil)
if err != nil {
print("bolt.Open: ")
println(err.Error())
} else {
println(db)
println("done!")
}
}
```
=> Fixes go syscallN being broken for mmap (and adds a few more file system sycalls for go).

changelog.d/+flush-console-logs.internal.md, mirrord/console/src/async_logger.rs, mirrord/console/src/logger.rs
While using the console alongside a debugger I noticed that some logs from lines that were executed were not showing up in the console. At some point the intproxy would exit without those logs ever being printed. Flushing after every log solved that.
It makes a big difference because the logs right before the process (either user app with layer or intproxy) exits are usually the most important and interesting.
I think efficiency is not a concern since the console is usually only used by us, not by users.
=> Flush console loggers after each log

changelog.d/+dirfd-crash-handled.fixed.md, mirrord/layer/src/file/hooks.rs, mirrord/layer/src/file/open_dirs.rs, mirrord/layer/src/file/ops.rs, mirrord/layer/tests/issue2001.rs
Happened when running
```
mirrord exec -t pod/pod sh
ls -la /run
```
=> Fix dirfd crashing on macOS by hooking dirfd

changelog.d/2152.fixed.md, mirrord/operator/src/setup.rs
Added userextras/oid to mirrord operator role to solve issues in some AKS Clusters
closes #2152
=> Added userextras/oid to mirrord operator role to solve issues in some AKS Clusters

changelog.d/+trace-only-fix.internal.md, mirrord/layer/src/detour.rs, mirrord/layer/src/lib.rs, mirrord/layer/src/setup.rs, mirrord/layer/src/socket/ops.rs
1. `fork` and `gethostname` detours still tried to talk to the internal proxy
2. removed unnecessary checks in `layer_start` function, we don't call it from the `fork` detour anymore
=> Fix trace only mode

changelog.d/+copies-in-status.changed.md, mirrord/cli/src/operator.rs, mirrord/config/src/target.rs, mirrord/operator/src/crd.rs
For https://github.com/metalbear-co/operator/issues/394.
New cli manually tested with old operator and there was no problem.
The new section of the status output looks like this:
```
No active copy targets.
```
or like this:
```
Active Copy Targets:
+-------------------------------+-----------+------------------------------+-------------+
| Original Target               | Namespace | Copy Pod Name                | Scale Down? |
+-------------------------------+-----------+------------------------------+-------------+
| deployment/py-serv-deployment | default   | mirrord-copy-job-wd8kj-2gvd4 | *           |
+-------------------------------+-----------+------------------------------+-------------+
```
=> Copy targets in operator status

changelog.d/+dlopen-fix.fixed.md, mirrord/layer/src/exec_utils.rs
Remove guard from dlopen, making calls from within dlopen hookable, potentially fixing issues
=> Remove guard from dlopen

changelog.d/+strict-config.changed.md, mirrord-schema.json, mirrord/config/src/feature/copy_target.rs, mirrord/config/src/feature/fs.rs, mirrord/config/src/feature/fs/mode.rs, mirrord/config/src/feature/network/incoming.rs, mirrord/config/src/feature/network/incoming/http_filter.rs, mirrord/config/src/feature/network/outgoing.rs, mirrord/config/src/target.rs, mirrord/config/src/util.rs
We had some users complaining about `http_header_filter` not working, while we removed it - many structs in our configuration already have the `deny_unknown_fields` flag but seems not all - we should keep adding this to any struct that is part of the mirrord configuration if not using `MirrordConfig` derive macro which does it automatically.
=> Change configuration parsing to be strict unallowing unknown fields

changelog.d/+ordered-dns.changed.md, mirrord/agent/src/dns.rs
Cluster DNS resolving now happens by nameserver order rather by statistics
=> Cluster DNS resolving now happens by nameserver order 

changelog.d/2193.fixed.md, mirrord/sip/src/error.rs, mirrord/sip/src/lib.rs
Closes #2193 and https://github.com/metalbear-co/mirrord/issues/976
The bug was that now (since #2182) that we also detect shebangs with spaces, when the sip-detection code was using the result of the shebang extraction as a path to the binary, that path contained whitespace, and so no sip was detected.
I changed the return type of the function that extracts the shebang to a struct to avoid further similar bugs.
We now test those cases with the public `sip_patch` function, (previously we only tested those cases with private functions, testing only part of the whole flow). 
I also eliminated all of the recursive-shebang stuff as we found out that's not allowed on darwin after originally writing that code.
=> Fix spaced shebang bug, remove recursions

Cargo.lock, changelog.d/+better-name-in-operator.added.md, mirrord/auth/Cargo.toml, mirrord/auth/src/credential_store.rs, mirrord/config/Cargo.toml, mirrord/operator/src/client.rs
```
No active copy targets.
Operator Daily Users: 1
Operator Monthly Users: 1
+------------------+-------------------+-----------+---------------------------------------------------------------+------------------+
| Session ID       | Target            | Namespace | User                                                          | Session Duration |
+------------------+-------------------+-----------+---------------------------------------------------------------+------------------+
| A7F36DD7C9432798 | namespace/default | N/A       | Aviram Hassan/aviram@metalbear.co@avirams-macbook-pro-2.local | 1s               |
+------------------+-------------------+-----------+---------------------------------------------------------------+------------------+
```
=> CLI now sends machine host + username to show in mirrord operator status

changelog.d/+mirrord-operator-tests.fixed.md, mirrord/operator/src/crd/label_selector.rs
I think we miss a call to `cargo clippy --all-targets` in the CI  :X
Not sure how it would work with our linux/macos targets though
=> Compilation error fixed

Cargo.lock, changelog.d/2202.fixed.md, mirrord/layer/src/common.rs, mirrord/layer/src/exec_utils.rs, mirrord/layer/src/lib.rs, mirrord/sip/Cargo.toml, mirrord/sip/src/error.rs, mirrord/sip/src/lib.rs, tests/go-e2e/go.mod, tests/go-e2e/go.sum
Fixes #2202 
1. Strip our tmp dir from the path in exec.
2. Do code signing on a temp file, and move the ready and signed file to the final location, because two processes might try to execute a binary at the same time and both of them trying to sign the same binary simultaneously leads to an error.
Also manually tested that this fixes the issue the way the user discovered it: by running a go application in vscode.
=> Make go run work on macOS with go 1.21

changelog.d/+unix-socket-falsely-sent.fixed.md, mirrord/layer/src/socket/ops.rs
Disabled unix sockets being wrongfully sent to the agent when socket isn't connected
=> Disabled unix sockets being wrongfully sent to the agent when socket isn't connected

changelog.d/+removed-incomplete-features.internal.md, mirrord/agent/src/main.rs, mirrord/kube/src/lib.rs
Just something I noticed randomly.
Currently we don't use any incomplete features, so I think we should remove this before someone enables a feature that `may function improperly in some or all cases` and `clippy` silently allows it
=> Remove incomplete features

changelog.d/+2239.added.md, mirrord/operator/src/client.rs
Closes #2239 
It was enough to simply remove fetching `TargetCrd` before creating `CopyTargetCrd`. This step was not actually necessary, we can construct `TargetCrd` struct without talking to the operator.
=> Allow to copy not ready targets

changelog.d/+incoming-config.fixed.md, mirrord/config/configuration.md, mirrord/config/src/feature/network/incoming.rs
Incoming traffic was being mirrord when set to `false`.
Also, document simple config version (mode only) and disabled (`false`).
=> Fix incoming set to false, improve docs

changelog.d/+use-proxy-applies-to-more.changed.md, mirrord/cli/src/execution.rs, mirrord/cli/src/main.rs, mirrord/cli/src/operator.rs, mirrord/cli/src/util.rs
use_proxy configuration now applies to mirrord operator status, and mirrord ls
=> use_proxy configuration now applies to more commands

changelog.d/2262.changed.md, mirrord/kube/src/api/kubernetes.rs, mirrord/kube/src/error.rs
=> change kubeconfig path expansion to use env as well

changelog.d/+internal-proxy-timeout.changed.md, mirrord/layer/src/lib.rs
Increase internal proxy timeout from 5 seconds to 10 seconds to fix long agent ops
=> Increase internal proxy timeout

changelog.d/+concurrent-dns-queries.added.md, mirrord/agent/src/dns.rs, mirrord/agent/src/error.rs, mirrord/agent/src/main.rs
1. All DNS queries are processes concurrently in the agent
2. DNS queries do not block the client session
=> Concurrent DNS queries (agent)

changelog.d/2283.fixed.md, mirrord/intproxy/src/proxies/simple.rs, mirrord/layer/src/error.rs, mirrord/layer/src/socket.rs, mirrord/layer/src/socket/ops.rs, mirrord/layer/tests/apps/issue2883.js, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/configs/outgoing_filter_local_not_existing_host.json, mirrord/layer/tests/issue2283.rs, tests/src/utils.rs
Closes #2283 
When the user app wants to initiate an outgoing connection, all outgoing filters are resolved in order to determine whether the connection should be done remotely or locally. The issue was that all resolution failures were treated as fatal errors (and were aborting the `connect` call). This PR filters out resolution errors which mean only that the name does not map to any known IP address (which is the case when the user puts a non-existent host in the filter).
Also, this PR adds a `GetAddrInfoResponse` cache on the internal proxy level. No need to do multiple dns queries each time an outgoing connection is initiated
=> Fixed DNS resolution in `OutgoingSelector`

.github/workflows/ci.yaml, changelog.d/2204.added.md, mirrord/layer/macro/src/lib.rs, mirrord/layer/src/error.rs, mirrord/layer/src/file/hooks.rs, mirrord/layer/src/file/ops.rs, mirrord/layer/tests/apps/issue2204/issue2204.rs, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/issue2204.rs
Closes #2204 
`statx` is not supported in Linux kernel prior to 4.11 or glibc prior to glibc 2.28. However, I don't see any problem with having this hooked, regardless of the user app's libc version. Either `statx` symbol is found and we should hook it or it's not found and nothing happens :eyes:
=> Hook `statx`

changelog.d/skip-kuma-containers.internal.md, mirrord/kube/src/api/container.rs
=> Add `kuma-sidecar` `kuma-init` to default list of skipped containers

changelog.d/+daemon-close-error.fixed.md, mirrord/cli/src/error.rs, mirrord/cli/src/execution.rs
Improved error display when something goes wrong with agent setup (agent immediately closes client connection with `DaemonMessage::Close`). We should not report as a bug.
Before:
After:
=> Improve error message when agent startup fails

changelog.d/+add-diagnose-command-latency.added.md, mirrord/cli/src/config.rs, mirrord/cli/src/connection.rs, mirrord/cli/src/diagnose.rs, mirrord/cli/src/error.rs, mirrord/cli/src/main.rs
Add a new command `mirrord diagnose latency` that enables users to check their network latency of the mirrord connection.
=> add `mirrord diagnose latency`

changelog.d/+50-better-agent-image-config.changed.md, mirrord-schema.json, mirrord/config/src/agent.rs, mirrord/config/src/lib.rs, mirrord/kube/src/api/container/ephemeral.rs, mirrord/kube/src/api/container/job.rs, mirrord/kube/src/api/container/util.rs, mirrord/layer/src/detour.rs, mirrord/layer/src/error.rs, mirrord/layer/src/file/ops.rs
- Issue: [#50](https://github.com/metalbear-co/charts/issues/50)
Changes the `agent.image` config to take an _advanced_ mode where you can specify `image.registry` and/or `image.tag`.
=> Better config for agent image.

changelog.d/2260.added.md, mirrord-schema.json, mirrord/cli/src/execution.rs, mirrord/cli/src/main.rs, mirrord/config/src/feature/env.rs
New config env.unset that allows user to unset environment variables in the executed process.
Closes #2260
=> New config env.unset that allows user to unset environment variables

.github/workflows/ci.yaml, changelog.d/+fix-e2e-on-release.internal.md
e2e failed because agent image of new tag wasn't released, so need to load it. to make sure it can download it we add a "needs" to wait for image to be built.
=> Fix e2e failing on release because image doesn't exist

changelog.d/+fix-panic.fixed.md, mirrord/layer/src/error.rs, mirrord/layer/src/macros.rs
User shared a crash report when process was stuck in a Panic<-> Frida loop, assumed to be caused by the panic from this flow.
=> Fixed layer making process zombie by calling panic from hookerror

.github/workflows/ci.yaml, .github/workflows/release.yaml, Cargo.lock, changelog.d/+update-rust-nightly-april.internal.md, medschool/src/main.rs, mirrord/agent/Dockerfile, mirrord/agent/src/steal/ip_tables/mesh.rs, mirrord/agent/src/steal/subscriptions.rs, mirrord/auth/src/credential_store.rs, mirrord/cli/src/config.rs, mirrord/config/derive/src/config/field.rs, mirrord/config/derive/src/config/flag.rs, mirrord/config/src/feature/fs/mode.rs, mirrord/intproxy/src/proxies/incoming/subscriptions.rs, mirrord/kube/src/api/runtime.rs, mirrord/layer/src/detour.rs, mirrord/layer/src/exec_utils.rs, mirrord/layer/src/file.rs, mirrord/layer/src/file/hooks.rs, mirrord/layer/src/go/linux_aarch64.rs, mirrord/layer/src/lib.rs, mirrord/layer/src/socket.rs, mirrord/layer/src/socket/hooks.rs, mirrord/layer/tests/apps/fileops/src/main.rs, mirrord/layer/tests/recv_from.rs, mirrord/operator/src/crd/label_selector.rs, rust-toolchain.toml, sample/rust/src/main.rs, tests/rust-e2e-fileops/src/main.rs, tests/src/issue1317.rs
Removing deprecated function call from `whoami`, and some unused stuff.
Bunch of clippy fixes.
With this, we should be able to run `cargo update` again.
=> Update nightly to 2024-04-15.

changelog.d/+ignoring-intellij-debug-worker.fixed.md, mirrord/layer/src/load.rs
Closes https://github.com/metalbear-co/mirrord-intellij/issues/258
Fixes mirrord compatibility with Rider 2024.1
=> Added JetBrains debugger to build tools

changelog.d/2400.fixed.md, mirrord/layer/src/socket/hooks.rs
implement dns_configuration_copy and dns_configuration_free on macOS to return null resolver, make it fallback to standard resolver in Netty situations
Closes #2400
=> Fix Netty native + macOS

changelog.d/+add-dns-config.added.md, mirrord-schema.json, mirrord/agent/src/dns.rs, mirrord/config/src/agent.rs, mirrord/config/src/lib.rs, mirrord/kube/src/api/container/ephemeral.rs, mirrord/kube/src/api/container/pod.rs, mirrord/kube/src/api/container/util.rs
People reported that specific domains can't resolve anymore post 3.93.1.
I checked the changes and couldn't see anything related besides those parameters, so I decided to make it configurable to see if it helps.
=> Add ability to configure DNS params for agent (timeout, attempts)

changelog.d/+value-hint-shell-completions-config-file.added.md, mirrord/cli/src/config.rs
Currently, shell completions for `mirrord exec --config-file <TAB><TAB>` only will complete to the next match of the path provided, and then assume it is done and append a space. We can provide a value_hint to the macro so that the generated completions only finish for a real file. Test like:
```bash
source <(cargo run completions bash)
mirrord exec --config-file ~/partial/path-<TAB><TAB>
```
*Open Question for Maintainers*: I only did this for the `exec` subcommand - is it the same config file used in all the other subcommands as well? If so, I can also add this value hint for them, just wasn't sure.
=> feat: `config_file` Shell Completions Hint for Files

changelog.d/+261-improve-tera-error.changed.md, mirrord/config/src/config.rs, mirrord/config/src/lib.rs
- Issue: [#261](https://github.com/metalbear-co/mirrord-intellij/issues/261)
Improves the error message we get when a tera template config error happens.
=> Improve tera templating error, by digging into the source.

changelog.d/2427.fixed.md, mirrord/agent/Cargo.toml, mirrord/agent/src/error.rs, mirrord/agent/src/main.rs
Closes #2427
`ip_tables_guard` in the agent now captures SIGTERM signals. When a signal is captured, child process (running real agent logic) is killed and the iptables are cleaned.
Additionally, `ip_tables_guard` now properly captures child process exit status and reports errors. Previously it would always discard the `.wait()` result, so errors in the agent logic were silenced (not reported in container status)
=> Agent graceful exit

changelog.d/+layer-comm-timeout.fixed.md, mirrord/intproxy/src/lib.rs, mirrord/intproxy/src/ping_pong.rs
Pings must be sent constantly, regardless of received agent->intproxy messages. Otherwise, we can be hitting layer communication timeouts in the operator
=> Send pings on fixed schedule (intproxy)

changelog.d/2163.internal.md, mirrord/config/src/feature/fs.rs
Closes #2163
Other tests already use the function [with_env_vars](https://github.com/metalbear-co/mirrord/blob/9b9ec7d8d84689a46d63fc768a906bd152ccb2d8/mirrord/config/src/util.rs#L204), it looks like this test was just forgotten. The test was accessing environment variables without a lock, causing it to fail if the environment was polluted by other tests.
=> Change flaky test to using with_env_vars

changelog.d/+mirrord-kube-errors.fixed.md, mirrord-schema.json, mirrord/config/src/agent.rs, mirrord/config/src/lib.rs, mirrord/kube/src/api/container.rs, mirrord/kube/src/api/container/ephemeral.rs, mirrord/kube/src/api/container/job.rs, mirrord/kube/src/api/container/pod.rs, mirrord/kube/src/api/container/targeted.rs, mirrord/kube/src/api/container/util.rs, mirrord/kube/src/api/kubernetes.rs, mirrord/kube/src/api/runtime.rs, mirrord/kube/src/error.rs
1. Made `RuntimeData::from_pod` public to avoid refetching multiple objects in the operator (no need to do n queries for deployment/rollout targets, consistent view of target state)
2. Improved `KubeApiError`. Error messages were starting with `mirrord-layer: `, which was confusing. Some errors produced really weird messages, like ```"mirrord-layer: Deployment: `Label for rollout: my-rollout, not found! not found!`"```
3. Payloads to kube POST requests are no longer constructed with `json!` macro and then parsed :skull: 
4. Changed `AgentConfig::image_pull_secrets` a bit to catch malformed secrets before attempting to create the agent and be more user friendly
=> Improve `mirrord-kube` errors

changelog.d/2367.added.md, mirrord/cli/src/extension.rs, mirrord/cli/src/main.rs
=> Give config info at session start

changelog.d/462.fixed.md, mirrord/kube/src/api/runtime.rs, mirrord/kube/src/error.rs
Closes #462 
Added some extra checks on the targeted pod (described in `RuntimeData::from_pod` doc). Example output when targeting a pod in deletion:
Additionaly, when targeting multi-pod deployments/rollouts, mirrord scans the list of matching pod and picks the first one that passes status check (instead of always using the first one on the list)
=> Verify target state before creating the agent

changelog.d/+concurrent-steal.fixed.md, mirrord/operator/src/client.rs, mirrord/operator/src/crd.rs
Port locks are already enforced in the operator + this check was buggy
=> Port lock check removed from CLI

changelog.d/+port-mapping-warning.added.md, mirrord/config/src/lib.rs
When you search for "port_mapping" on our discord server, most of the results are configuration files that contain a port mapping that maps each port their application uses to that same identical port.
Let's help users declutter their config files and be less confused, by explaining that field if they don't understand it and nudge them to remove unnecessary mappings.
=> Add warning for unnecessary port mappings

CONTRIBUTING.md, changelog.d/+update-contributing.internal.md
Added section to the end of the contributing guide with info about switching the rust-analyzer build target for OS-specific code
=> Update contributing guide

changelog.d/+remove-baidu.internal.md, tests/node-e2e/outgoing/test_outgoing_traffic_many_requests.mjs
See example flake here: https://github.com/metalbear-co/mirrord/actions/runs/9450763078/job/26030239466?pr=2486#step:10:252
I don't know that this is not actually an issue with mirrord, but since [we removed the last website with which the tests often flaked](https://github.com/metalbear-co/mirrord/pull/2471) I'm assuming we can just remove this one as well.
=> Remove from tests host name that often can't be found

.github/workflows/ci.yaml, changelog.d/+fix-ci-race.internal.md
Fix race in CI e2e waiting for wrong job -  test_agent instead of test_agent_image
=> Fix race in CI e2e waiting for wrong job - 

Cargo.lock, changelog.d/2539.fixed.md, mirrord/agent/src/cli.rs, mirrord/kube/src/api/container/util.rs, mirrord/protocol/Cargo.toml, mirrord/protocol/src/lib.rs
=> fix network interface agent config not propagating to agent

changelog.d/+fallible-operator-detection.changed.md, mirrord/cli/src/connection.rs, mirrord/cli/src/error.rs
The clients encountered some `503`s from discovery api and had to explicitly disable the operator. A warning and fallback to OSS should be more user friendly
=> Ignore operator discovery errors

changelog.d/+medschool-order.changed.md, mirrord/config/configuration.md
After #2424 medschool produces a documentation markdown file with a different content order than before.
In order to separate this change from any other change to the configuration docs, I want to merge the new `configuration.md`.
Running medschool when changing the config docs and pushing the changed file, on every PR that changes the docs is important because it helps the PR sender and reviewer check that the new docs will be added to the markdown file correctly (were added in the right place of the source code, etc).
I did not check myself that the new file contains everything it should. I hope `medschool` was not broken and the output is valid. The length of the file changed, but there could have been PRs that made changes to the docs without rerunning `medschool`, idk. But I guess …
=> rerun medschool after medschool change

Cargo.lock, Cargo.toml, changelog.d/2466.internal.md, mirrord/cli/src/connection.rs, mirrord/cli/src/error.rs, mirrord/cli/src/main.rs, mirrord/cli/src/operator.rs, mirrord/cli/src/operator/session.rs, mirrord/intproxy/src/agent_conn.rs, mirrord/kube/src/api/kubernetes.rs, mirrord/operator/src/client.rs, mirrord/operator/src/client/conn_wrapper.rs, mirrord/operator/src/client/discovery.rs, mirrord/operator/src/client/error.rs, mirrord/operator/src/client/upgrade.rs, mirrord/operator/src/lib.rs, mirrord/operator/src/types.rs
Closes #2466 
CLI version and user name/hostname headers are sent with all operator requests.
Client certificate header:
1. `mirrord operator status`: we don't know operator license fingerprint before getting the resource, so header is not sent.
2. `mirrord exec`: as soon as we get the operator resource, we prepare the client cert header. If we fail, command aborts.
3. `mirrord ls` / `mirrord operator session`: as soon as we get the operator resource, we try to prepare the client cert header. If we fail, we continue without it
I kind of went full aggro on the operator client code and made more changes than necessary :V
1. Copied to `mirrord ls` the extra discovery step present in `mirrord exec` (https://github.com/metalbear-co/mirrord/issues/2487)
2. Moved some parts of operator client …
=> Extend operator headers

Cargo.lock, Cargo.toml, changelog.d/2529.fixed.md, mirrord/agent/src/entrypoint.rs, mirrord/agent/src/error.rs, mirrord/agent/src/main.rs, mirrord/agent/src/sniffer.rs, mirrord/agent/src/sniffer/api.rs, mirrord/agent/src/sniffer/messages.rs, mirrord/agent/src/sniffer/tcp_capture.rs, mirrord/agent/src/util.rs
Closes #2529 
1. `TcpConnectionSniffer` uses `broadcast` channels (capacity - 512 TCP packets) to send incoming data in a non-blocking way.
2. `TcpSnifferApi` notifies the client about closed connection (and sends an error log) when it's `broadcast::Receiver` is lagging.
3. `TcpConnectionSniffer` notifies `TcpSnifferApi`s about new connections via `mpsc` channels (capacity - 128 new sniffed connections). When a new connection is sniffed, the sniffer attempts to notify each client without blocking. If the client already has 128 queued new connections, client is not notified. There's some space for improvement here - instead of dropping new connection, we could be dropping the oldest one in the queue. However, `mpsc::Sender`'s api does not allow for it and we would need to implement some …
=> Improve mirroring for high stress

changelog.d/1730.changed.md, mirrord/cli/src/connection.rs, mirrord/cli/src/error.rs, mirrord/cli/src/main.rs, mirrord/cli/src/operator.rs, mirrord/cli/src/operator/session.rs, mirrord/operator/src/client.rs
Closes #1730 
Running API discovery always when we fail to fetch operator resource (also if user explicitly enabled operator or the command requires it). Provides a better error message to the user.
Now it looks like this:
=> Always run discovery when fetching operator fails

changelog.d/+dotnet-debug-env.fixed.md, mirrord/agent/src/env.rs
Add exclusion for DOTNET_EnableDiagnostics  to make DotNet debugging work by default
=> Add exclusion for DOTNET_EnableDiagnostics 

.github/workflows/ci.yaml, changelog.d/+mirrord-operator-crate.internal.md, mirrord/cli/src/error.rs, mirrord/cli/src/main.rs, mirrord/operator/src/client.rs, mirrord/operator/src/client/error.rs, mirrord/operator/src/crd.rs, mirrord/operator/src/crd/kube_target.rs
I found myself fixing the same thing again, so I added an extra CI check for this
=> Fix mirrord-operator compilation with only `crd` feature enabled

changelog.d/2582.fixed.md, mirrord/kube/src/api/runtime.rs
=> Don't include non-running pods in node capacity check

changelog.d/2590.fixed.md, mirrord/agent/src/steal/connection.rs
=> Fix empty request streaming hanging forever

changelog.d/2576.added.md, mirrord-schema.json, mirrord/config/src/experimental.rs, mirrord/layer/src/lib.rs, mirrord/layer/src/setup.rs, mirrord/layer/src/tls.rs
Added experimental.trust_any_certificate to enable making app trust any certificate on macOS. Closes #2576
Supersedes #2576
=> Added experimental.trust_any_certificate

changelog.d/2597.fixed.md, mirrord/layer/src/socket.rs
Remove automatic ignore of incoming/outgoing traffic for ports high ports 50000-60000
This was a patch we had back in the day to handle debuggers, but since then we have other means to support it (DebuggerPorts impl)
closes #2597
=> Remove automatic ignore of incoming/outgoing traffic for ports high ports

changelog.d/+warn-multiple-containers.added.md, mirrord/kube/src/api/container.rs, mirrord/kube/src/api/container/job.rs, mirrord/kube/src/api/kubernetes.rs, mirrord/kube/src/api/runtime.rs
* When there are multiple containers on the target, and the user did not specify a target container, show a warning with 
the chosen container name.
Currently shows only when not connected to an operator. Adding that warning when running with the operator is a bit more complicated because we don't have the target resource (pod/deployment/etc.) at the client side. So we would need to send back a signal that a warning should be displayed. I think we should leave that to a separate PR as this PR is just a quick detour to pick low hanging fruit.
* Also, added Knative's "queue-proxy" container to the skipped list.
=> Warn when automatically picking a container out of many

changelog.d/721.fixed.md, mirrord-schema.json, mirrord/config/configuration.md, mirrord/config/src/target.rs
- Issue: #721 
The error reported in the issue seems to have been fixed at some point:
Looks like vscode allows a string there now.
=> Remove invalid schema doc mentioning `podname` as a valid pod target selector.

changelog.d/+debugger-detection.fixed.md, mirrord/layer/src/debugger_ports.rs
Fixes https://github.com/metalbear-co/mirrord-vscode/issues/137 along with PR https://github.com/metalbear-co/mirrord-vscode/pull/138
=> Update arguments layout in debugpy/VSCode debugger port detection

.github/workflows/ci.yaml, changelog.d/+tweak-container-command.internal.md, mirrord/cli/src/config.rs, mirrord/cli/src/container.rs, mirrord/cli/src/main.rs
Do some manual parsing to allow the following syntax
```
mirrord container -t deploy/my-target -- podman run ...
```
=> Tweak mirrord container command

Cargo.lock, changelog.d/+agent-improvements.internal.md, mirrord/agent/src/entrypoint.rs, mirrord/agent/src/error.rs, mirrord/agent/src/file.rs, mirrord/agent/src/outgoing.rs, mirrord/agent/src/outgoing/udp.rs, mirrord/agent/src/runtime.rs, mirrord/agent/src/runtime/crio.rs, mirrord/agent/src/runtime/error.rs, mirrord/agent/src/sniffer.rs, mirrord/agent/src/sniffer/api.rs, mirrord/agent/src/steal.rs, mirrord/agent/src/steal/api.rs, mirrord/agent/src/steal/connection.rs, mirrord/agent/src/util.rs, mirrord/layer/src/error.rs, mirrord/protocol/Cargo.toml, mirrord/protocol/src/error.rs
Some minor improvements to agent code:
1. `TcpStealerApi` no longer need to hold a shared channel permit to close session with the background task
2. Removed last uses `IndexAllocator`
3. Added some more logs to outgoing task
4. Improved agent errors
=> Agent housekeeping

changelog.d/+sqs-crd-case.changed.md, mirrord/operator/src/crd.rs
I missed some CRD fields and forgot to `serde(rename)` them.
Everything works as is, but these field names are not in the correct case according to k8s conventions.
One of those fields is user-facing - `spec.consumer.workload_type` in `MirrordWorkloadQueueRegistry` should be `workloadType`.
This change is breaking, but I think almost nobody installed those CRDs yet, also, the feature is marked unstable. We would need to make the same change in the helm chart too, and release an operator.
Since this is a matter of conventions, we could also avoid breaking compatibility and leave everything as is, but I would rather fix it.
=> Rename CRD fields to camelCase

.github/workflows/release.yaml, changelog.d/homebrew-shasum-ci.fixed.md
https://github.com/metalbear-co/mirrord/pull/2655 changed the download artifact step to only download `shasum` artifact. This effectively changed destination path (no `shasum` parent dir, files are extracted to straight to `/tmp/artifacts`)
=> Fix homebrew shasum

changelog.d/ls-concurrency.internal.md, mirrord/kube/src/api/kubernetes/seeker.rs
The original issue should be fixed with https://github.com/metalbear-co/mirrord/pull/2734
=> Restored concurrent list requests in `mirrord ls`

changelog.d/2518.changed.md, mirrord/agent/src/file.rs, mirrord/config/src/lib.rs, mirrord/intproxy/src/proxies/simple.rs, mirrord/layer/src/detour.rs, mirrord/layer/src/file/ops.rs, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/configs/readlink.json, mirrord/layer/tests/readlink.rs
=> Make readlink stable (enabled by default) now, with the protocol part gated on version support.

changelog.d/2750.changed.md, mirrord/cli/src/internal_proxy.rs
- Issue: #2750 
Without a file type, it's very annoying to upload it :sweat:
=> Add .log as a file type for the default intproxy logs.

changelog.d/2788.fixed.md, mirrord/kube/src/api/kubernetes.rs, mirrord/kube/src/api/runtime.rs
=> handle cases where pod has ipv6

changelog.d/+add-exit-error.added.md, mirrord/cli/src/internal_proxy.rs
This error https://github.com/metalbear-co/mirrord/issues/2788
could've been diagnosed easily given it was marked as an error, and logged by default by the new settings.
=> internal proxy now explicitly logs exit errors

Cargo.lock, changelog.d/2609.added.md, mirrord/cli/Cargo.toml, mirrord/cli/src/config.rs, mirrord/cli/src/error.rs, mirrord/cli/src/main.rs, mirrord/cli/src/port_forward.rs, mirrord/intproxy/src/lib.rs, mirrord/intproxy/src/proxies/incoming.rs
=> Reverse port-forwarding

Cargo.lock, Cargo.toml, changelog.d/+update-tonic-deps.changed.md, mirrord/agent/Cargo.toml, mirrord/agent/src/runtime.rs, mirrord/agent/src/runtime/crio.rs
```bash
cargo tree -i tonic
tonic v0.12.3
├── containerd-client v0.5.0 (https://github.com/metalbear-co/rust-extensions.git?branch=update-tonic#af863098)
│   └── mirrord-agent v3.118.1 (/Users/tal/Documents/projects/mirrord/mirrord/agent)
├── k8s-cri v0.9.0
│   └── mirrord-agent v3.118.1 (/Users/t4lz/projects/mirrord/mirrord/agent)
└── mirrord-agent v3.118.1 (/Users/t4lz/projects/mirrord/mirrord/agent)
```
=> update deps to not use tonic 0.11

Cargo.lock, changelog.d/2817.fixed.md, mirrord/cli/src/port_forward.rs, mirrord/layer/Cargo.toml, mirrord/layer/src/setup.rs, mirrord/layer/tests/issue2817.rs
=> Fixed `all_of` and `any_of` HTTP filters

changelog.d/+nodeselector.added.md, mirrord-schema.json, mirrord/config/configuration.md, mirrord/config/src/agent.rs, mirrord/kube/src/api/container/job.rs, mirrord/kube/src/api/container/pod.rs
Hello, this is my first PR so please go easy on me.
When I run `mirrord exec` I missed the option to tell the agent on which node to spawn, so I added the functionality after seeing that `labels` and `annotations` were already supported (since they're more or less the same, except node selector sits under the `spec` key).
I tested it on my own cluster using this config JSON:
```json
{
"agent": {
"node_selector":
{
"node1": "label1"
}
}
}
```
I was interested in adding this option in the CLI too, but this seemed like a quicker proof-of-concept. If this is something you're willing to merge, I can work on the CLI version as well.
Let me know what you think 😄
=> Add nodeSelector option to agent config

changelog.d/2869.fixed.md, mirrord/cli/src/container.rs, mirrord/cli/src/execution.rs, mirrord/cli/src/main.rs
=> Fixed `mirrord-intproxy` lingering when executing a non-existent binary

changelog.d/2876.added.md, mirrord-schema.json, mirrord/config/configuration.md, mirrord/config/src/agent.rs, mirrord/kube/src/api/container/job.rs, mirrord/kube/src/api/container/pod.rs
Added the option to specify a serviceAccount in the config file as mentioned [here](https://github.com/metalbear-co/mirrord/issues/2876).
=> Add serviceAccount option to agent config

changelog.d/2894.changed.md, mirrord-schema.json, mirrord/config/configuration.md, mirrord/config/src/agent.rs, mirrord/config/src/feature/fs/advanced.rs
- Issue: #2894 
Just add a notice to the docs, does not fix relative path mapping.
=> Add notice that fs mapping does not apply to relative paths.

changelog.d/+better-name-for-result-and-config-param.internal.md, mirrord/cli/src/connection.rs, mirrord/cli/src/container.rs, mirrord/cli/src/diagnose.rs, mirrord/cli/src/error.rs, mirrord/cli/src/execution.rs, mirrord/cli/src/extension.rs, mirrord/cli/src/external_proxy.rs, mirrord/cli/src/extract.rs, mirrord/cli/src/internal_proxy.rs, mirrord/cli/src/main.rs, mirrord/cli/src/operator.rs, mirrord/cli/src/operator/session.rs, mirrord/cli/src/verify_config.rs, mirrord/cli/src/vpn.rs, mirrord/operator/src/client.rs
- Issue: n/a
1. Renames the `Result` type we have for `cli` to `CliResult`;
2. Renames some `config` args to `layer_config`, where it could be confused with kube config.
=> Rename some potentially confusing names.

changelog.d/+mirrord-container-publish.changed.md, mirrord/cli/src/config.rs, mirrord/cli/src/container.rs, mirrord/cli/src/container/command_builder.rs
Add a warning to `mirrord container` command if `-p` is provided as part of run command.
=> mirrord container port-publish warning

changelog.d/+build-mac-args.internal.md, scripts/build_fat_mac.sh
My main motivation was cargo's `--offline`.
=> Forward build script args to cargo build

changelog.d/+escape-regexes.fixed.md, mirrord/layer/src/file/filter/read_local_by_default.rs
Otherwise, a path like "/my/cool/executable (1)" would be used in the regex, and that regex would not match that path (it would match "/my/cool/executable 1").
=> Escape paths used in regexes

changelog.d/+operator-setup-permissions.internal.md, mirrord/cli/src/config.rs, mirrord/cli/src/operator.rs, mirrord/operator/src/setup.rs
add a clusterrole rule to allow applications integration
```yaml
- apiGroups:
- argoproj.io
resources:
- applications
verbs:
- list
- get
- patch
```
=> Add operator permissions for argocd appications

changelog.d/+scaledown-prep.internal.md, mirrord/kube/src/api/kubernetes/rollout.rs, mirrord/operator/src/setup.rs
New scaledown implementation in the operator patches replicas directly in the workload spec (to keep things nice and simple)
=> Scaledown prep

changelog.d/2927.fixed.md, mirrord/cli/src/container.rs, mirrord/cli/src/container/command_builder.rs, mirrord/cli/src/main.rs
For mirrord container command check that the sidecar container is started after it is created when running with docker runtime
relevant for #2927
=> mirrord container docker check run

changelog.d/2947.fixed.md, mirrord/sip/Cargo.toml, mirrord/sip/src/lib.rs
Fix #2947 
The sbt script installed via `cs`, has some non-textual data at the end:
So in order to support that case, we now only read the first line when we parse the shebang (makes sense anyways), and when we create a patched script, we don't try to read the contents of the file to a string, we just copy over the bytes.
=> Support non-utf8 scripts in SIP handling

changelog.d/+no-stdout-sidecar-start.internal.md, mirrord/cli/src/container.rs
#2933 added a start patch but unintentionally added a small print that is piped from the underlying command, this removes the print.
=> Prevent unintended stdout print

changelog.d/+629-sqs-operator-status.added.md, mirrord/cli/src/error.rs, mirrord/cli/src/operator.rs, mirrord/cli/src/operator/status.rs, mirrord/kube/src/api/kubernetes/seeker.rs, mirrord/operator/src/client.rs, mirrord/operator/src/client/error.rs, mirrord/operator/src/crd.rs
- Issue: https://github.com/metalbear-co/operator/issues/629
- Related PRs: https://github.com/metalbear-co/operator/pull/692
Adds SQS to `mirrord operator status`.
=> Add SQS to mirrord operator status reporting.

changelog.d/+79-bogus-websocket-reset.fixed.md, mirrord/cli/src/execution.rs, mirrord/cli/src/main.rs, mirrord/operator/src/client.rs
- Issue: https://github.com/metalbear-co/private/issues/79
=> Add a tokio sleep after MirrordExecution::start so we can await on it and drive the runtime, preventing the websocket reset.

changelog.d/+kafka-secret-permission.internal.md, mirrord/operator/src/setup.rs
Related to #2953 - the operator needs explicit access to read Secrets from the cluster
=> Add 'mirrord-operator-secret-access' role to operator

changelog.d/2962.fixed.md, mirrord/cli/src/port_forward.rs
Changed the ping/pong routine of `ReversePortForwarder` to match that of `PortForwarder` - this prevents the timeout being repeatedly reset when recieving messages more frequently than every 30 seconds (causing the ping to never be sent)
=> Stop mirrord ending unexpectedly when port forwarding in reverse

changelog.d/+block-mirroring-policy.added.md, mirrord/operator/src/crd.rs
I tried versioning `MirrordPolicy`, but to no success. In a scenario when the cluster has the new policy and the operator does not recognize it, there are only two options:
1. Operator will fail to deserialize this policy
2. Operator will silently ignore the new blocked feature
This is because `kube::Api` fetches and attempts to deserialize all resources of the given kind, regardless of their version
Since option 1 is less scary, we can as well just add another enum variant, without introducing the versioning boilerplate.
I also added a catch-all variant to prevent this problem in the future.
=> Add `MirrordPolicy` that blocks traffic mirroring

changelog.d/2988.fixed.md, mirrord/layer/src/go/linux_x64.rs, mirrord/layer/tests/apps/issue2988/go.mod, mirrord/layer/tests/apps/issue2988/main.go, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/issue2988.rs
=> Fix Go >=1.23.3 crash due to running hook in vfork

Cargo.lock, changelog.d/2936.fixed.md, mirrord/cli/src/container.rs, mirrord/cli/src/execution.rs, mirrord/cli/src/extension.rs, mirrord/cli/src/external_proxy.rs, mirrord/cli/src/internal_proxy.rs, mirrord/cli/src/main.rs, mirrord/config/Cargo.toml, mirrord/config/src/agent.rs, mirrord/config/src/config.rs, mirrord/config/src/container.rs, mirrord/config/src/experimental.rs, mirrord/config/src/external_proxy.rs, mirrord/config/src/feature.rs, mirrord/config/src/feature/copy_target.rs, mirrord/config/src/feature/env.rs, mirrord/config/src/feature/fs/advanced.rs, mirrord/config/src/feature/network.rs, mirrord/config/src/feature/network/dns.rs, mirrord/config/src/feature/network/incoming.rs, mirrord/config/src/feature/network/incoming/http_filter.rs, mirrord/config/src/feature/network/outgoing.rs, mirrord/config/src/internal_proxy.rs, mirrord/config/src/lib.rs
=> Prevent config rendering on every process

CONTRIBUTING.md, Cargo.lock, changelog.d/2958.added.md, mirrord/agent/src/dns.rs, mirrord/agent/src/entrypoint.rs, mirrord/config/src/feature/network.rs, mirrord/intproxy/protocol/src/lib.rs, mirrord/intproxy/src/background_tasks.rs, mirrord/intproxy/src/lib.rs, mirrord/intproxy/src/proxies/simple.rs, mirrord/layer/src/file/ops.rs, mirrord/layer/src/socket.rs, mirrord/layer/src/socket/ops.rs, mirrord/layer/tests/dns_resolve.rs, mirrord/layer/tests/issue2055.rs, mirrord/layer/tests/issue2283.rs, mirrord/protocol/Cargo.toml, mirrord/protocol/src/codec.rs, mirrord/protocol/src/dns.rs, tests/src/traffic.rs, tests/src/traffic/steal.rs, tests/src/utils.rs
=> DNS resolution for IPv6

changelog.d/+targetless-tolerations.fixed.md, mirrord-schema.json, mirrord/config/configuration.md, mirrord/config/src/agent.rs, mirrord/kube/src/api/container/job.rs, mirrord/kube/src/api/container/pod.rs
- Issue: https://github.com/metalbear-co/operator/issues/737
=> Add tolerations for targetless agent.

changelog.d/1706.fixed.md, mirrord/cli/src/config.rs
part of https://github.com/metalbear-co/mirrord/issues/1706
=> feat: use default config path when no arg for -f is provided

changelog.d/+set-agent-port.internal.md, mirrord/cli/src/connection.rs, mirrord/kube/src/api/container.rs, mirrord/kube/src/api/kubernetes.rs
https://github.com/metalbear-co/private/issues/141
=> Allow agent port to be configurable

.github/workflows/ci.yaml, Cargo.lock, changelog.d/3044.fixed.md, mirrord/agent/src/file.rs, mirrord/intproxy/protocol/src/lib.rs, mirrord/intproxy/src/proxies/files.rs, mirrord/layer/src/file.rs, mirrord/layer/src/file/hooks.rs, mirrord/layer/src/file/ops.rs, mirrord/layer/src/go/linux_x64.rs, mirrord/layer/src/go/mod.rs, mirrord/layer/tests/apps/fileops/go/main.go, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/fileops.rs, mirrord/protocol/Cargo.toml, mirrord/protocol/src/codec.rs, mirrord/protocol/src/file.rs, tests/go-e2e-statfs/go.mod, tests/go-e2e-statfs/main.go, tests/src/file_ops.rs, tests/src/utils.rs
Might prevent #3044 
We were already calling statfs64 in the agent.
Now sending back all of the statfs64 data back to the client with a new message type.
Added new statfs64 detours, and reactivated the Go detour, using the statfs64 detours.
Added an E2E test that runs Go's statfs in a deployed test image and with mirrord, and compares the result (we do not require the exact same data, because some fields change from call to call).
=> statfs in Go on Linux

changelog.d/+local-http-connection-timeout.added.md, mirrord-schema.json, mirrord/cli/src/internal_proxy.rs, mirrord/cli/src/main.rs, mirrord/cli/src/port_forward.rs, mirrord/config/configuration.md, mirrord/config/src/experimental.rs, mirrord/intproxy/src/lib.rs, mirrord/intproxy/src/proxies/incoming.rs, mirrord/intproxy/src/proxies/incoming/http/client_store.rs, mirrord/intproxy/src/proxies/incoming/http_gateway.rs, mirrord/layer/tests/common/mod.rs
Issue #3072
The situation improved when we started reusing local connections, which eliminated long-standing idle connections. My suspicion is that the user application does not handle multiple open HTTP connections very well. With this config, they'll be able to have the connections killed right after the request
=> Made idle timeout configurable for local HTTP clients

Cargo.lock, changelog.d/+less-trace-spam.internal.md, mirrord/intproxy/src/proxies/incoming.rs, mirrord/protocol/Cargo.toml, mirrord/protocol/src/tcp.rs
Printing full headers creates a lot of spam, especially since they're printed in parent spans. Sometimes multiple times. And `cookie` alone can be quite long.
=> Print full request/response headers only once in intproxy

changelog.d/+mirrord-kube-improvements.internal.md, mirrord/kube/src/api.rs, mirrord/kube/src/api/container/ephemeral.rs, mirrord/kube/src/api/container/job.rs, mirrord/kube/src/api/kubernetes.rs, mirrord/kube/src/api/kubernetes/portforwarder.rs, mirrord/kube/src/api/runtime.rs
* Improved logging in `wrap_raw_connection`
* Namespaces of the agent pod and the target pod are now non-optional (they were always `Some` anyway)
* Removed unnecessary "agent_version" field - has not been used for a long time
* Incluster version of `KubernetesAPI::create_connection` now takes connect info via reference
=> Some mirrord-kube improvements

changelog.d/3120.changed.md, mirrord/agent/src/entrypoint.rs, mirrord/agent/src/steal.rs, mirrord/agent/src/steal/api.rs, mirrord/agent/src/steal/connection.rs, mirrord/agent/src/steal/connections.rs, mirrord/agent/src/steal/connections/filtered.rs, mirrord/agent/src/steal/http/filter.rs
* Steal API now sends type StealerMessage to the agent, which can contain either DaemonTcp or LogMessage.
* If an HTTP request matches more than one filter, the request is forwarded to the first matching client, while the other matching clients recevive a warning via LogMessage.
=> Warn clients of matching HTTP requests that went to another client (#3120)

changelog.d/+pod-template-permissions.fixed.md, mirrord/cli/src/extension.rs, mirrord/operator/src/setup.rs
We need to fetch the workload ref when preparing the session
=> Added missing permissions for `PodTemplate`s

changelog.d/+mirrord-profil.added.md, mirrord-schema.json, mirrord/cli/src/container.rs, mirrord/cli/src/error.rs, mirrord/cli/src/extension.rs, mirrord/cli/src/main.rs, mirrord/cli/src/profile.rs, mirrord/cli/src/verify_config.rs, mirrord/config/configuration.md, mirrord/config/src/config/context.rs, mirrord/config/src/lib.rs, mirrord/operator/src/crd.rs, mirrord/operator/src/crd/profile.rs, mirrord/operator/src/setup.rs, tests/src/operator.rs, tests/src/operator/profiles.rs, tests/src/utils.rs
Example profile:
```yaml
apiVersion: profiles.mirrord.metalbear.co/v1alpha
kind: MirrordProfile # clusterwide resource
metadata:
name: mirror-and-outgoing-local
spec:
featureAdjustments:
- kind: incoming
change: mirror
- kind: outgoing
change: off
- kind: dns
change: off
```
=> MirrordProfile

Cargo.lock, changelog.d/3184.fixed.md, mirrord/sip/Cargo.toml, mirrord/sip/src/codesign.rs, mirrord/sip/src/lib.rs
Fix #3184 
Recently the method of signing SIP-patched binaries on macOS was changed, and apparently the library that is now used has a different default behaviour than the cli tool used before.
When re-signing with the CLI, any existing entitlements are cleared. When signing with the library, they remain, unless overwritten with a plist passed in xml format.
Since the patched binary was no longer signed by the entity that was granted those entitlements, the signature was invalid and the process was killed by `taskgated`.
So in order to clear any entitlements the binary might have, we set a constant xml plist that contains an empty entitlement dict.
In addition, we also change the identifier, as the codesign man page says we should, to my understanding.
I'll also add a small unit test for …
=> Fix running binaries with entitlements on macOS

changelog.d/+sip-regression-tests.internal.md, mirrord/sip/src/lib.rs
Part of #3149 and #3184.
The fixes were already merged, now adding regression tests for those two regressions.
=> Add unit tests for recent SIP-regressions

CHANGELOG.md, changelog.d/+ghrc-cache.internal.md, changelog.d/+laxer-ping-pong.changed.md, changelog.d/3212.fixed.md
Version in `Cargo.toml` is already at 3.137.0, but the release failed
=> 3.137.0-fixed

changelog.d/+e2e-apps-fixed.internal.md, tests/node-e2e/app.mjs, tests/python-e2e/app_fastapi.py, tests/python-e2e/app_flask.py, tests/src/http.rs, tests/src/operator/concurrent_steal.rs, tests/src/traffic/steal.rs
3 test HTTP servers (node, python fastapi, python flask) were implemented to exit after receiving a `DELETE` request. This was introducing flakes - in the test code we were expecting a correct response, but reading the response body was often failing with IO errors.
I don't think there's any reason to implement graceful exit logic in these apps, since the tests do verify what they're meant to verify anyway.
=> Fixed test HTTP servers

changelog.d/+test-using-queue-url.internal.md, tests/rust-sqs-printer/src/main.rs, tests/src/operator/queue_splitting.rs, tests/src/utils/sqs_resources.rs
For testing https://github.com/metalbear-co/operator/issues/807
Also - change the localstack setup to match the playground's so that they can be run on the same local cluster and share the localstack service and the operator.
=> Change SQS-splitting E2E test to use a queue URL instead of queue name for one of the queues

.github/workflows/ci.yaml, Cargo.lock, changelog.d/+separate-redirector-task.internal.md, mirrord/agent/Cargo.toml, mirrord/agent/iptables/src/chain.rs, mirrord/agent/iptables/src/error.rs, mirrord/agent/src/entrypoint.rs, mirrord/agent/src/entrypoint/setup.rs, mirrord/agent/src/error.rs, mirrord/agent/src/file.rs, mirrord/agent/src/incoming.rs, mirrord/agent/src/incoming/composed.rs, mirrord/agent/src/incoming/connection.rs, mirrord/agent/src/incoming/error.rs, mirrord/agent/src/incoming/iptables.rs, mirrord/agent/src/incoming/steal_handle.rs, mirrord/agent/src/incoming/task.rs, mirrord/agent/src/main.rs, mirrord/agent/src/metrics.rs, mirrord/agent/src/outgoing.rs, mirrord/agent/src/outgoing/udp.rs, mirrord/agent/src/sniffer.rs, mirrord/agent/src/steal/api.rs, mirrord/agent/src/steal/connection.rs, mirrord/agent/src/steal/connections.rs, mirrord/agent/src/steal/subscriptions.rs, tests/src/traffic/steal.rs
Preparation for passthrough traffic mirroring.
Since both stealing and mirroring will use iptables redirections, we need to extract this logic from the stealer.
=> Separate traffic redirector task

.devcontainer/Dockerfile, .devcontainer/devcontainer-lock.json, .devcontainer/devcontainer.json, changelog.d/+dev-contrainer-config.changed.md
* Current docker base image we use was archived. Replaced it with the one maintained in [devcontainers/images](https://github.com/devcontainers/images).
* Addressed all warnings in `devcontainer.json` configuration file
* removed discontinued vscode extension
* add `protoc` feature
* move vscode settings under the recommended JSON key path
=> chore: refresh devcontainer configuration

changelog.d/+dotnet-env-var.changed.md, mirrord/agent/src/env.rs
When not excluded .NET tries to load dlls from a location that is on the target container.
=> Exclude DOTNET_STARTUP_HOOKS env var by default

changelog.d/+3167.changed.md, mirrord/kube/src/api/container/ephemeral.rs, mirrord/kube/src/api/container/job.rs
The updated progress message looks like the following:
* when spawning a mirrord agent as an ephemeral container inside a target pod
```
⠒ mirrord exec
✓ running on latest (3.137.0)!
✓ ready to launch process
✓ layer extracted
✓ operator not found
✓ container created
✓ mirrord-agent-vujeksdvd1 container is ready in py-serv-deployment-5949cc9645-qvkcf pod and default namespace
✓ arm64 layer library extracted
✓ config summary 
```
* when spawning a mirrord agent as a pod in the cluster
```
⠐ mirrord exec
✓ running on latest (3.137.0)!
✓ ready to launch process
✓ layer extracted
✓ operator not found
✓ agent pod created
✓ mirrord-agent-p9vnpnflcs-dxh8x pod is ready in default namespace
✓ arm64 layer library extracted
✓ config summary 
```
=> Improve mirrord CLI progress message

changelog.d/+3178.added.md, mirrord/cli/src/config.rs, mirrord/cli/src/operator.rs, mirrord/cli/src/operator/session.rs
Add `-f` option for specifying mirrord config file for `mirrord operator session` sub commands.
=> Add config file arg for operator session commands

changelog.d/+verify-queue-deletion.internal.md, tests/src/operator/queue_splitting.rs, tests/src/utils/sqs_resources.rs
The SQS operator creates SQS queues for SQS splitting. When the clients exit those queues should be deleted. Now this is verified in the E2E test.
=> Verify queue deletion after clients exit in SQS E2E test

changelog.d/+834.changed.md, mirrord/operator/src/setup.rs
- Issue: https://github.com/metalbear-co/operator/issues/843
=> Adds a reflector for caching mirrord policies (changes mirrord operat…or setup to have the operator with watch permission for policies).

Cargo.lock, changelog.d/+list-targets-by-type.added.md, mirrord-schema.json, mirrord/cli/src/config.rs, mirrord/cli/src/list.rs, mirrord/cli/src/verify_config.rs, mirrord/config/Cargo.toml, mirrord/config/src/target.rs, mirrord/kube/src/api/kubernetes/seeker.rs, mirrord/kube/src/error.rs
https://linear.app/metalbear/issue/MBE-739/intellij-stuck-forever-listing
=> Allow targets to be listed by specific resource type

changelog.d/mirorrdprofile.changed.md, mirrord/cli/src/profile.rs, mirrord/config/src/lib.rs, mirrord/operator/src/crd/profile.rs, mirrord/operator/src/setup.rs, tests/src/operator/profiles.rs
`MirrordProfile` was introduced in #3181. The linked PR
* adds the `MirrordProfile`  **cluster-wise** CRD
* writes the yaml in set up output
* fetch the resource and apply it to the configuration if profile identifier is specified in user's config
We later realized that we want to add a namespaced profile CRD as well. Thus, we will have to rename `MirrordProfile` to `MirrordClusterProfile` to follow the same kube resource naming convention.
In this PR, we add the `MirrordClusterProfile` which is identical to the existing one but has the desired name/kind. We stop exposing the old mirrord profile CRD in setup (charts need to be updated as well for this). In the operator, we will throw a warning to the user if any old profile CRD or CR is detected and ask the user to migrate. During the …
=> Rename mirrord profile to cluster profile

Cargo.lock, changelog.d/+skip-build-tools.added.md, deny.toml, mirrord-schema.json, mirrord/config/configuration.md, mirrord/config/src/lib.rs, mirrord/layer/src/load.rs
Adds a new config option enabling users to supply custom build tools they would like to "skip," e.g. not load into the layer. This can be helpful if you build and execute your binary in a single command. There was an existing set of well known build tools, so we simply decided to extend that static list with config.
=> support for MIRRORD_SKIP_EXTRA_BUILD_TOOLS

changelog.d/+iptables-cleanup.fixed.md, mirrord/agent/src/entrypoint.rs
With IPv6 enabled, the agent is only using the ip6tables. It should use both iptables and ip6tables
=> Fix iptables check and cleanup

changelog.d/+namespaced-profile.added.md, mirrord/cli/src/profile.rs, mirrord/operator/src/crd/profile.rs, mirrord/operator/src/setup.rs, tests/src/operator/profiles.rs
Before merging, confirm that all users' `MirrordProfile` CRs are migrated to `MirrordClusterProfile` and the old `MirrordProfile` CRD is removed.
Depend on https://github.com/metalbear-co/charts/pull/196 being released and applied by users first.
=> namespaced mirrrod profile

changelog.d/3373.changed.md, mirrord/cli/src/extract.rs
mirrord now extracts layer to temp_dir()/mirrord to allow easier whitelisting with Carbon Black
=> mirrord now extracts layer to temp_dir()/mirrord 

changelog.d/+sqs-e2e-config-map.internal.md, tests/src/operator/queue_splitting.rs
Seems like with the version from the operator's `main`, at least on my sick, old system, the tests need longer timeouts to pass.
Also added some helpful prints to the tests.
=> Small improvements to SQS E2E tests

Cargo.lock, changelog.d/3407.added.md, mirrord-schema.json, mirrord/cli/src/execution.rs, mirrord/cli/src/extension.rs, mirrord/cli/src/main.rs, mirrord/config/src/experimental.rs, mirrord/layer/src/exec_utils.rs, mirrord/layer/src/lib.rs, mirrord/layer/tests/bash.rs, mirrord/layer/tests/common/mod.rs, mirrord/layer/tests/fileops.rs, mirrord/layer/tests/sip.rs, mirrord/sip/Cargo.toml, mirrord/sip/src/lib.rs
```
[1752748605] (pid 22090, binary: /Users/gem/sdk/go1.24.1/pkg/tool/darwin_arm64/compile, args: Some(["/Users/gem/sdk/go1.24.1/bin/go", "build", "-o", "./application", "./main.go"])) SIP Status: Ok(SipBinary("/Users/gem/sdk/go1.24.1/pkg/tool/darwin_arm64/compile")), layer load type: None
[1752748605] (pid 22090) SIP patch result: patched successfully
```
=> Add logging to a file while patching SIP

changelog.d/+agent-reuse-addr.fixed.md, mirrord/agent/src/entrypoint.rs
Agent communication port now uses SO_REUSEADDR flag, fixing cases where agent port is reused in a fast consecutive manner and fails
=> Agent communication port now uses SO_REUSEADDR flag

changelog.d/+add-port-fwder-ready.fixed.md, mirrord/cli/src/main.rs
Issue: https://linear.app/metalbear/issue/MBE-1012/add-ready-progress-message-to-port-forwarding
=> Add Ready message to port-forward cmd progress

changelog.d/+python-e2e-apps-stdout.internal.md, tests/python-e2e/app_fastapi.py, tests/python-e2e/app_flask.py
I believe we read mangled output from Python E2E apps, see [this failure](https://github.com/metalbear-co/mirrord/actions/runs/16648023970/job/47113327516?pr=3465):
```
Making HTTP connection 1
Making HTTP request 1 in connection 1
Sending request
Received response 200 OK. BODY=Ok("Echo [remote]: GET 1:1"), HEADERS={"content-length": "22", "content-type": "text/plain; charset=utf-8", "date": "Thu, 31 Jul 2025 11:50:45 GMT"}
Making HTTP request 2 in connection 1
Sending request
Received response 200 OK. BODY=Ok("Echo [remote]: GET 1:2"), HEADERS={"content-length": "22", "content-type": "text/plain; charset=utf-8", "date": "Thu, 31 Jul 2025 11:50:45 GMT"}
Making HTTP connection 2
Making HTTP request 1 in connection 2
Sending request
stdout 11:50:45 33756: GET: Request completedGET: Request …
```
=> Synchronize prints in python e2e apps

Cargo.lock, changelog.d/3457.fixed.md, mirrord/kube/src/api/kubernetes.rs
Issue: https://linear.app/metalbear/issue/MBE-1324/mirrord-treats-kubeconfig-as-single-file-instead-of-list
=> Fix incorrect parsing of PATH-like `kubeconfig` config file values

changelog.d/+hide-progress-implementations.internal.md, mirrord/cli/Cargo.toml, mirrord/progress/Cargo.toml, mirrord/progress/src/implementations.rs, mirrord/progress/src/lib.rs
Right now dependents unnecessarily pull in `indicatif`, `enum_dispatch` and `serde`
(changed loc come from the fact that code from `lib.rs` was moved to a separate file)
=> Hide `mirrord_progress::Progress` implementations behind a crate feature

changelog.d/+add-ignore-containers-config.added.md, mirrord-schema.json, mirrord/config/configuration.md, mirrord/config/src/feature/copy_target.rs, mirrord/operator/src/client.rs, mirrord/operator/src/crd/copy_target.rs
Issue: https://linear.app/metalbear/issue/MBE-1330/allow-user-to-remove-init-containers-in-copy-target
=> Allow users to ignore containers and init containers in copy target config

changelog.d/+agent-hanging.fixed.md, mirrord/agent/src/incoming/task.rs
Just saw 35MB of "Gracefully shutting down a redirected HTTP connection" logs :skull: 
`CancellationToken::cancelled` immediately returns `Poll::Ready` when the token has already been cancelled, so the task was never returning control to the runtime
=> Fixed incoming HTTP connection shutdown (mirrord-agent)

changelog.d/+codesign-filename.changed.md, mirrord/sip/src/codesign.rs, mirrord/sip/src/lib.rs
Hopeful try for MBE-1366
Before, the identifier looked like `mirrord-patched-bin-2f0bf90efc71519a0a52884873ce877cbde13bca`, now it looks like `zsh-e9b62e761b8f7382dd4baf7eeb7f7f5a480128bd`, which is kind of what the identifier looks like when signed with `codesign`, only we do random hex and maybe for codesign it's some checksum or hash, idk.
https://linear.app/metalbear/issue/MBE-1366/sip-issue-manual-patch-works-mirrord-patch-fails
=> Use the file name in the identifier of the new signed file when patching for SIP

changelog.d/3508.added.md, mirrord-schema.json, mirrord/cli/src/container/sidecar.rs, mirrord/config/configuration.md, mirrord/config/src/container.rs
- Issue: https://github.com/metalbear-co/mirrord/issues/3508
Also changed the default path from `/tmp/mirrord-tls.pem` to `/mirrord/mirrord-tls.pem`.
=> Added config for specifying mirrord-tls.pem path when using mirrord container command.

Cargo.lock, changelog.d/+intproxy-bg-task-cancel.internal.md, mirrord/intproxy/Cargo.toml, mirrord/intproxy/src/agent_conn.rs, mirrord/intproxy/src/background_tasks.rs, mirrord/intproxy/src/proxies/incoming/http_gateway.rs, mirrord/intproxy/src/proxies/incoming/tcp_proxy.rs
1. Tasks for delivering stolen HTTP messages are now properly cancelled when the connection is closed from the agent side.
2. Agent reconnect is cancelled when the intproxy is entering the failover state.
=> Improve intproxy bg tasks

changelog.d/+sqs-prometheus-e2e-test.internal.md, tests/src/operator/queue_splitting.rs, tests/src/utils/sqs_resources.rs
Closes https://linear.app/metalbear/issue/INT-201/test-sqs-prometheus-metrics-in-e2e
https://github.com/metalbear-co/operator/pull/1063 has to be merged first, so that if the operator is updated to a new mirrord crate version, CI doesn't fail.
And I also want to verify the test passes on CI before merging. Testing in this manual workflow with a test branch https://github.com/metalbear-co/operator/actions/runs/17865079044
=> Verify correct Prometheus metrics in SQS E2E tests

Cargo.lock, Cargo.toml, deny.toml
=> Update minhook-detours-rs dependency to git
